# image builder base on golang:1.21.1-alpine3.18
FROM golang@sha256:0c860c7ceba62231d0f99fb92e9d7c1577f26fea794a12c75756a8f64b146e45 as builder

WORKDIR /validator-test/

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 go test -v -c -o validator-test ./test/application-connectivity-validator/

FROM scratch

COPY --from=builder /validator-test/validator-test /
ENTRYPOINT [ "/validator-test" ]
CMD ["-test.v"]
