FROM eu.gcr.io/kyma-project/external/golang:1.17.6-alpine3.15 as builder

ENV SRC_DIR=/test-gateway-app
WORKDIR $SRC_DIR
COPY . $SRC_DIR

RUN go mod download

RUN go build -v -o test-gateway-app ./cmd/test-gateway-app

FROM eu.gcr.io/kyma-project/external/alpine:3.15.4
COPY --from=builder /test-gateway-app/test-gateway-app .
CMD ["/test-gateway-app"]