NAMESPACE ?= test
GOPATH ?= $(shell go env GOPATH)
DIRECTOR_URL=https://compass-gateway-auth-oauth.$(COMPASS_HOST)/director/graphql
TOKENS_ENDPOINT=https://oauth2.${COMPASS_HOST}/oauth2/token

COMPASS_TEST_IMAGE = "$(DOCKER_PUSH_REPOSITORY)$(DOCKER_PUSH_DIRECTORY)/compass-runtime-agent-test:$(DOCKER_TAG)"
TEST_TIMEOUT = "3m"

.PHONY: release test image clean
.PHONY: test-compass-runtime-agent test-compass-runtime-agent-debug clean-compass-runtime-agent-test image-compass-runtime-agent-test publish-compass-runtime-agent-test

test: test-compass-runtime-agent
clean: clean-compass-runtime-agent-test

test-compass-runtime-agent: test-compass-runtime-agent-debug clean-compass-runtime-agent-test

test-compass-runtime-agent-debug:
	@echo $(GOPATH)/bin/go-junit-report --help
	kubectl create namespace $(NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	kubectl label namespace $(NAMESPACE) istio-injection=enabled --overwrite

	@helm template resources/charts/compass-runtime-agent-test \
	--set namespace=$(NAMESPACE) \
	--set compassCredentials.clientID=$(COMPASS_CLIENT_ID) \
	--set compassCredentials.clientSecret=$(COMPASS_CLIENT_SECRET) \
	--set compassCredentials.tokensEndpoint=$(TOKENS_ENDPOINT) \
	--set directorUrl=$(DIRECTOR_URL) \
    | kubectl apply -f -

	-kubectl wait --for=condition=complete --timeout=$(TEST_TIMEOUT) -n $(NAMESPACE) job/compass-runtime-agent-test
	@echo ""
	@echo "Compass test results:"

	./scripts/check-pod-logs.sh compass-runtime-agent-test

clean-compass-runtime-agent-test:
	helm template resources/charts/compass-runtime-agent-test  | kubectl delete -f -
	kubectl delete ns $(NAMESPACE) --ignore-not-found

