# -*- mode: makefile -*-

NAMESPACE ?= test
GOPATH ?= $(shell go env GOPATH)

MOCK_SERVICE_NAME="mock-application"
APP_URL = "$(MOCK_SERVICE_NAME).$(NAMESPACE).svc.cluster.local"
TEST_TIMEOUT = "3m"
MAKEFILE_NAME=Makefile.test-application-gateway

.PHONY: test clean
.PHONY: test-gateway test-gateway-debug clean-gateway-test disable-sidecar-for-mtls-test enable-sidecar-after-mtls-test generate-certs

test: test-gateway
clean: clean-gateway-test

test-gateway: disable-sidecar-for-mtls-test generate-certs create-resources
	if kubectl wait --for=condition=complete --timeout=$(TEST_TIMEOUT) -n $(NAMESPACE) job/application-gateway-test; then \
	echo "Success! Results:"; \
	./scripts/check-pod-logs.sh application-gateway-test; \
	$(MAKE) clean-gateway-test -f $(MAKEFILE_NAME); \
	else \
	echo "Tests failed! Results:"; \
	./scripts/check-pod-logs.sh application-gateway-test; \
	$(MAKE) clean-gateway-test -f $(MAKEFILE_NAME); \
	exit 1; \
	fi

test-gateway-debug: disable-sidecar-for-mtls-test generate-certs create-resources
	kubectl wait --for=condition=complete --timeout=$(TEST_TIMEOUT) -n $(NAMESPACE) job/application-gateway-test; \
	echo "Results:"; \
	./scripts/check-pod-logs.sh application-gateway-test; \

create-resources:
	kubectl create namespace $(NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	kubectl label namespace $(NAMESPACE) istio-injection=enabled --overwrite

	@helm template resources/charts/gateway-test/charts/mock-app \
        --set global.namespace=$(NAMESPACE) \
        --set mockServiceName=$(MOCK_SERVICE_NAME) \
        --values resources/charts/gateway-test/values.yaml \
    | kubectl apply -f -
	kubectl rollout status deployment mock-application -n test --timeout=90s

	helm template resources/charts/gateway-test/charts/test \
		--set namespace=$(NAMESPACE) \
		--set mockServiceName=$(MOCK_SERVICE_NAME) \
		--values resources/charts/gateway-test/values.yaml \
    | kubectl apply -f -

clean-gateway-test:
	helm template resources/charts/gateway-test --set namespace=$(NAMESPACE) | kubectl delete -f -
	kubectl delete ns $(NAMESPACE) --ignore-not-found

disable-sidecar-for-mtls-test:
	kubectl -n kyma-system patch deployment central-application-gateway -p '{"spec":{"template":{"metadata":{"annotations":{"traffic.sidecar.istio.io/excludeOutboundPorts": "8090,8091"}}}}}'
	kubectl rollout status deploy central-application-gateway -n kyma-system --timeout=1m

enable-sidecar-after-mtls-test:
	kubectl -n kyma-system patch deployment central-application-gateway --type=json --patch '[{ "op": "remove", "path": "/spec/template/metadata/annotations/traffic.sidecar.istio.io~1excludeOutboundPorts"}]'

generate-certs:
	./scripts/generate-self-signed-certs.sh $(APP_URL) ./resources/charts/gateway-test/charts/test/certs/positive
	./scripts/generate-self-signed-certs.sh $(APP_URL) ./resources/charts/gateway-test/charts/test/certs/negative
	./scripts/generate-self-signed-certs.sh test-other-ca ./resources/charts/gateway-test/charts/test/certs/invalid-ca
	cp -p -R ./resources/charts/gateway-test/charts/test/certs ./resources/charts/gateway-test/charts/mock-app
