// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha1 "github.com/kyma-project/kyma/components/application-operator/pkg/apis/applicationconnector/v1alpha1"
)

// AppManager is an autogenerated mock type for the AppManager type
type AppManager struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, name, options
func (_m *AppManager) Get(ctx context.Context, name string, options v1.GetOptions) (*v1alpha1.Application, error) {
	ret := _m.Called(ctx, name, options)

	var r0 *v1alpha1.Application
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v1alpha1.Application); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, application, options
func (_m *AppManager) Update(ctx context.Context, application *v1alpha1.Application, options v1.UpdateOptions) (*v1alpha1.Application, error) {
	ret := _m.Called(ctx, application, options)

	var r0 *v1alpha1.Application
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Application, v1.UpdateOptions) *v1alpha1.Application); ok {
		r0 = rf(ctx, application, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Application, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, application, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
