export const UserSidebar = [
  { text: 'Back to Kyma CLI', link: '/cli/user/README', collapsed: true },
  { text: 'kyma', link: '/cli/user/gen-docs/kyma' },
  { text: 'kyma alpha', link: '/cli/user/gen-docs/kyma_alpha' },
  { text: 'kyma alpha app', link: '/cli/user/gen-docs/kyma_alpha_app' },
  { text: 'kyma alpha app push', link: '/cli/user/gen-docs/kyma_alpha_app_push' },
  { text: 'kyma alpha hana', link: '/cli/user/gen-docs/kyma_alpha_hana' },
  { text: 'kyma alpha hana map', link: '/cli/user/gen-docs/kyma_alpha_hana_map' },
  { text: 'kyma alpha kubeconfig', link: '/cli/user/gen-docs/kyma_alpha_kubeconfig' },
  { text: 'kyma alpha kubeconfig generate', link: '/cli/user/gen-docs/kyma_alpha_kubeconfig_generate' },
  { text: 'kyma alpha provision', link: '/cli/user/gen-docs/kyma_alpha_provision' },
  { text: 'kyma alpha reference-instance', link: '/cli/user/gen-docs/kyma_alpha_reference-instance' },
  { text: 'kyma completion', link: '/cli/user/gen-docs/kyma_completion' },
  { text: 'kyma completion bash', link: '/cli/user/gen-docs/kyma_completion_bash' },
  { text: 'kyma completion fish', link: '/cli/user/gen-docs/kyma_completion_fish' },
  { text: 'kyma completion powershell', link: '/cli/user/gen-docs/kyma_completion_powershell' },
  { text: 'kyma completion zsh', link: '/cli/user/gen-docs/kyma_completion_zsh' },
  { text: 'kyma help', link: '/cli/user/gen-docs/kyma_help' },
  { text: 'kyma module', link: '/cli/user/gen-docs/kyma_module' },
  { text: 'kyma module add', link: '/cli/user/gen-docs/kyma_module_add' },
  { text: 'kyma module catalog', link: '/cli/user/gen-docs/kyma_module_catalog' },
  { text: 'kyma module delete', link: '/cli/user/gen-docs/kyma_module_delete' },
  { text: 'kyma module list', link: '/cli/user/gen-docs/kyma_module_list' },
  { text: 'kyma module manage', link: '/cli/user/gen-docs/kyma_module_manage' },
  { text: 'kyma module unmanage', link: '/cli/user/gen-docs/kyma_module_unmanage' },
  { text: 'kyma version', link: '/cli/user/gen-docs/kyma_version' }
];
