// Code generated by mockery v1.0.0
package automock

import bundle "github.com/kyma-project/kyma/components/helm-broker/internal/bundle"
import mock "github.com/stretchr/testify/mock"

// BundleSyncer is an autogenerated mock type for the BundleSyncer type
type BundleSyncer struct {
	mock.Mock
}

// AddProvider provides a mock function with given fields: url, p
func (_m *BundleSyncer) AddProvider(url string, p bundle.Provider) {
	_m.Called(url, p)
}

// CleanProviders provides a mock function with given fields:
func (_m *BundleSyncer) CleanProviders() {
	_m.Called()
}

// Execute provides a mock function with given fields:
func (_m *BundleSyncer) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
