// Code generated by mockery v1.0.0
package automock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/kyma-project/kyma/components/helm-broker/internal/bundle"
)

// BundleSyncer is an autogenerated mock type for the BundleSyncer type
type BundleSyncer struct {
	mock.Mock
}

// AddProvider provides a mock function with given fields: url, p
func (_m *BundleSyncer) AddProvider(url string, p bundle.Provider) {
	_m.Called(url, p)
}

// CleanProviders provides a mock function with given fields:
func (_m *BundleSyncer) CleanProviders() {
	_m.Called()
}

// Execute provides a mock function with given fields:
func (_m *BundleSyncer) Execute() {
	_m.Called()
}
