package automock

import chart "k8s.io/helm/pkg/proto/hapi/chart"
import mock "github.com/stretchr/testify/mock"

// ChartUpserter is an autogenerated mock type for the ChartUpserter type
type ChartUpserter struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: c
func (_m *ChartUpserter) Upsert(c *chart.Chart) (bool, error) {
	ret := _m.Called(c)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*chart.Chart) bool); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*chart.Chart) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
