// Code generated by mockery v1.0.0
package automock

import bundle "github.com/kyma-project/kyma/components/helm-broker/internal/bundle"
import mock "github.com/stretchr/testify/mock"

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// ProvideBundles provides a mock function with given fields: URL
func (_m *Provider) ProvideBundles(URL string) ([]bundle.CompleteBundle, error) {
	ret := _m.Called(URL)

	var r0 []bundle.CompleteBundle
	if rf, ok := ret.Get(0).(func(string) []bundle.CompleteBundle); ok {
		r0 = rf(URL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bundle.CompleteBundle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(URL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
