{
 "title": "Compass / Kyma Environment Broker",
 "tags": [
  "kyma-environment-broker",
  "compass"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Runtime Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(compass_keb_instances_total)"
    }
   ]
  },
  {
   "title": "Top 16 number of instances per Global Account ID",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(16, compass_keb_global_account_id_instances_total{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "{{`{{global_account_id}}`}}"
    }
   ]
  },
  {
   "title": "Total number of Global Acocunts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(compass_keb_global_account_id_instances_total)"
    }
   ]
  },
  {
   "title": "In progress provisioning operations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(compass_keb_operations_provisioning_in_progress_total)"
    }
   ]
  },
  {
   "title": "In progress deprovisioning operations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(compass_keb_operations_deprovisioning_in_progress_total)"
    }
   ]
  },
  {
   "title": "Operations success ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(SUM(compass_keb_operations_provisioning_succeeded_total) / (SUM(compass_keb_operations_provisioning_failed_total) + SUM(compass_keb_operations_provisioning_succeeded_total))) * 100",
     "legendFormat": "Provisioning"
    },
    {
     "expr": "(SUM(compass_keb_operations_deprovisioning_succeeded_total) / (SUM(compass_keb_operations_deprovisioning_failed_total) + SUM(compass_keb_operations_deprovisioning_succeeded_total))) * 100",
     "legendFormat": "Deprovisioning"
    }
   ]
  },
  {
   "title": "Operation time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "avg by (service) (rate(compass_keb_provisioning_duration_minutes_sum{job=\"compass-kyma-environment-broker\"}[1h]) / rate(compass_keb_provisioning_duration_minutes_count{job=\"compass-kyma-environment-broker\"}[1h]))",
     "legendFormat": "Provisioning"
    },
    {
     "expr": "avg by (service) (rate(compass_keb_deprovisioning_duration_minutes_sum{job=\"compass-kyma-environment-broker\"}[40m]) / rate(compass_keb_deprovisioning_duration_minutes_count{job=\"compass-kyma-environment-broker\"}[40m]))",
     "legendFormat": "Deprovisioning"
    }
   ]
  },
  { "title": "Broker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_gc_duration_seconds{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "{{`{{quantile}}`}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_goroutines{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_threads{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_alloc_bytes{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "avg by (service) (rate(go_memstats_alloc_bytes_total{service=\"compass-kyma-environment-broker\"}[1m]))",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "sum by (service) (go_memstats_stack_inuse_bytes{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "sum by (service) (go_memstats_heap_inuse_bytes{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (process_open_fds{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "DB connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service) (go_sql_stats_connections_idle{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg by (service) (go_sql_stats_connections_max_open{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "Max open"
    },
    {
     "expr": "avg by (service) (go_sql_stats_connections_in_use{service=\"compass-kyma-environment-broker\"})",
     "legendFormat": "In use"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"compass-kyma-environment-broker.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "{{`{{container}}`}}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{pod=~\"compass-kyma-environment-broker.*\"})",
     "legendFormat": "{{`{{container}}`}} - Requests"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{pod=~\"compass-kyma-environment-broker.*\"})",
     "legendFormat": "{{`{{container}}`}} - Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"compass-kyma-environment-broker.*\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "{{`{{container}}`}}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{pod=~\"compass-kyma-environment-broker.*\"})",
     "legendFormat": "{{`{{container}}`}} - Requests"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_cpu_cores{pod=~\"compass-kyma-environment-broker.*\"})",
     "legendFormat": "{{`{{container}}`}} - Limit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_network_receive_bytes_total{pod=~\"compass-kyma-environment-broker.*\"}[1m])))",
     "legendFormat": "compass-kyma-environment-broker"
    }
   ]
  }
 ]
}