// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kyma-project/kyma/components/ui-api-layer/pkg/apis/ui/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BackendModuleLister helps list BackendModules.
type BackendModuleLister interface {
	// List lists all BackendModules in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.BackendModule, err error)
	// BackendModules returns an object that can list and get BackendModules.
	BackendModules(namespace string) BackendModuleNamespaceLister
	BackendModuleListerExpansion
}

// backendModuleLister implements the BackendModuleLister interface.
type backendModuleLister struct {
	indexer cache.Indexer
}

// NewBackendModuleLister returns a new BackendModuleLister.
func NewBackendModuleLister(indexer cache.Indexer) BackendModuleLister {
	return &backendModuleLister{indexer: indexer}
}

// List lists all BackendModules in the indexer.
func (s *backendModuleLister) List(selector labels.Selector) (ret []*v1alpha1.BackendModule, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BackendModule))
	})
	return ret, err
}

// BackendModules returns an object that can list and get BackendModules.
func (s *backendModuleLister) BackendModules(namespace string) BackendModuleNamespaceLister {
	return backendModuleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BackendModuleNamespaceLister helps list and get BackendModules.
type BackendModuleNamespaceLister interface {
	// List lists all BackendModules in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.BackendModule, err error)
	// Get retrieves the BackendModule from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.BackendModule, error)
	BackendModuleNamespaceListerExpansion
}

// backendModuleNamespaceLister implements the BackendModuleNamespaceLister
// interface.
type backendModuleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BackendModules in the indexer for a given namespace.
func (s backendModuleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BackendModule, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BackendModule))
	})
	return ret, err
}

// Get retrieves the BackendModule from the indexer for a given namespace and name.
func (s backendModuleNamespaceLister) Get(name string) (*v1alpha1.BackendModule, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("backendmodule"), name)
	}
	return obj.(*v1alpha1.BackendModule), nil
}
