
build:
	docker build -t gcr.io/sap-sekymaongcpmarketplace/gke-dep:1.0 .


push:
	docker push gcr.io/sap-sekymaongcpmarketplace/gke-dep:1.0
	
test:
	docker build -t gcr.io/sap-sekymaongcpmarketplace/gke-dep:test .
	docker push gcr.io/sap-sekymaongcpmarketplace/gke-dep:test
