FROM maven:3.6-jdk-11
WORKDIR /build

#Compile and install SDK locally
COPY serverless-java-sdk serverless-java-sdk
RUN (cd serverless-java-sdk && mvn clean package install)

COPY ./pom.xml .
RUN mvn dependency:go-offline

# Create runtime
COPY ./src ./src
RUN mvn compile
