#!/usr/bin/env sh

LATEST_TAG="latest"
RELEASE_CHANGELOG_FILE_DIRECTORY="./.changelog/"
RELEASE_CHANGELOG_FILE_PATH="${RELEASE_CHANGELOG_FILE_DIRECTORY}release-changelog.md"
FULL_CHANGELOG_FILE_PATH="./CHANGELOG.md"
FULL_CHANGELOG_TEMP_FILE_PATH="./temp.md"