// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import apperrors "github.com/kyma-project/kyma/components/proxy-service/internal/apperrors"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Get provides a mock function with given fields: name
func (_m *Repository) Get(name string) (string, string, apperrors.AppError) {
	ret := _m.Called(name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 apperrors.AppError
	if rf, ok := ret.Get(2).(func(string) apperrors.AppError); ok {
		r2 = rf(name)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(apperrors.AppError)
		}
	}

	return r0, r1, r2
}
