// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"
	director "github.com/kyma-project/kyma/components/compass-runtime-agent/internal/compass/director"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/kyma/components/compass-runtime-agent/internal/kyma/model"
)

// DirectorClient is an autogenerated mock type for the DirectorClient type
type DirectorClient struct {
	mock.Mock
}

// FetchConfiguration provides a mock function with given fields:
func (_m *DirectorClient) FetchConfiguration() ([]model.Application, graphql.Labels, error) {
	ret := _m.Called()

	var r0 []model.Application
	if rf, ok := ret.Get(0).(func() []model.Application); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Application)
		}
	}

	var r1 graphql.Labels
	if rf, ok := ret.Get(1).(func() graphql.Labels); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(graphql.Labels)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetURLsLabels provides a mock function with given fields: urlsCfg, actualLabels
func (_m *DirectorClient) SetURLsLabels(urlsCfg director.RuntimeURLsConfig, actualLabels graphql.Labels) (graphql.Labels, error) {
	ret := _m.Called(urlsCfg, actualLabels)

	var r0 graphql.Labels
	if rf, ok := ret.Get(0).(func(director.RuntimeURLsConfig, graphql.Labels) graphql.Labels); ok {
		r0 = rf(urlsCfg, actualLabels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graphql.Labels)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(director.RuntimeURLsConfig, graphql.Labels) error); ok {
		r1 = rf(urlsCfg, actualLabels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
