// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import tls "crypto/tls"

// ProxyConfigurator is an autogenerated mock type for the ProxyConfigurator type
type ProxyConfigurator struct {
	mock.Mock
}

// SetURLAndCerts provides a mock function with given fields: directorURL, cert
func (_m *ProxyConfigurator) SetURLAndCerts(directorURL string, cert *tls.Certificate) error {
	ret := _m.Called(directorURL, cert)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *tls.Certificate) error); ok {
		r0 = rf(directorURL, cert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
