// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"

// BrokerSyncer is an autogenerated mock type for the brokerSyncer type
type BrokerSyncer struct {
	mock.Mock
}

// SyncBroker provides a mock function with given fields: namespace
func (_m *BrokerSyncer) SyncBroker(namespace string) error {
	ret := _m.Called(namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
