// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import apperrors "github.com/kyma-project/kyma/components/proxy-service/internal/apperrors"

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// Strategy is an autogenerated mock type for the Strategy type
type Strategy struct {
	mock.Mock
}

// AddAuthorizationHeader provides a mock function with given fields: r
func (_m *Strategy) AddAuthorizationHeader(r *http.Request) apperrors.AppError {
	ret := _m.Called(r)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(*http.Request) apperrors.AppError); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Invalidate provides a mock function with given fields:
func (_m *Strategy) Invalidate() {
	_m.Called()
}
