// Code generated by "stringer -type=FunctionEventType -trimprefix=FunctionEventType"; DO NOT EDIT.

package controllers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FunctionEventTypeWarning-1]
	_ = x[Normal-2]
}

const _FunctionEventType_name = "WarningNormal"

var _FunctionEventType_index = [...]uint8{0, 7, 13}

func (i FunctionEventType) String() string {
	i -= 1
	if i < 0 || i >= FunctionEventType(len(_FunctionEventType_index)-1) {
		return "FunctionEventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FunctionEventType_name[_FunctionEventType_index[i]:_FunctionEventType_index[i+1]]
}
