// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	ui_v1alpha1 "github.com/kyma-project/kyma/components/idppreset/pkg/apis/ui/v1alpha1"
	versioned "github.com/kyma-project/kyma/components/idppreset/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kyma-project/kyma/components/idppreset/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kyma-project/kyma/components/idppreset/pkg/client/listers/ui/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IDPPresetInformer provides access to a shared informer and lister for
// IDPPresets.
type IDPPresetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IDPPresetLister
}

type iDPPresetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIDPPresetInformer constructs a new informer for IDPPreset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIDPPresetInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIDPPresetInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredIDPPresetInformer constructs a new informer for IDPPreset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIDPPresetInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().IDPPresets().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().IDPPresets().Watch(options)
			},
		},
		&ui_v1alpha1.IDPPreset{},
		resyncPeriod,
		indexers,
	)
}

func (f *iDPPresetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIDPPresetInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iDPPresetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ui_v1alpha1.IDPPreset{}, f.defaultInformer)
}

func (f *iDPPresetInformer) Lister() v1alpha1.IDPPresetLister {
	return v1alpha1.NewIDPPresetLister(f.Informer().GetIndexer())
}
