// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenCache is an autogenerated mock type for the TokenCache type
type TokenCache struct {
	mock.Mock
}

// Add provides a mock function with given fields: clientID, token, expirationSeconds
func (_m *TokenCache) Add(clientID string, token string, expirationSeconds int) {
	_m.Called(clientID, token, expirationSeconds)
}

// Get provides a mock function with given fields: clientID
func (_m *TokenCache) Get(clientID string) (string, bool) {
	ret := _m.Called(clientID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(clientID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(clientID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: clientID
func (_m *TokenCache) Remove(clientID string) {
	_m.Called(clientID)
}
