// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/kyma-project/kyma/components/api-controller/pkg/clients/gateway.kyma.cx/clientset/versioned/typed/gateway.kyma.cx/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGatewayV1alpha2 struct {
	*testing.Fake
}

func (c *FakeGatewayV1alpha2) Apis(namespace string) v1alpha2.ApiInterface {
	return &FakeApis{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGatewayV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
