// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	uiv1alpha1 "github.com/kyma-project/kyma/common/microfrontend-client/pkg/apis/ui/v1alpha1"
	versioned "github.com/kyma-project/kyma/common/microfrontend-client/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kyma-project/kyma/common/microfrontend-client/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kyma-project/kyma/common/microfrontend-client/pkg/client/listers/ui/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MicroFrontendInformer provides access to a shared informer and lister for
// MicroFrontends.
type MicroFrontendInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MicroFrontendLister
}

type microFrontendInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMicroFrontendInformer constructs a new informer for MicroFrontend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMicroFrontendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMicroFrontendInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMicroFrontendInformer constructs a new informer for MicroFrontend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMicroFrontendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().MicroFrontends(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().MicroFrontends(namespace).Watch(context.TODO(), options)
			},
		},
		&uiv1alpha1.MicroFrontend{},
		resyncPeriod,
		indexers,
	)
}

func (f *microFrontendInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMicroFrontendInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *microFrontendInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&uiv1alpha1.MicroFrontend{}, f.defaultInformer)
}

func (f *microFrontendInformer) Lister() v1alpha1.MicroFrontendLister {
	return v1alpha1.NewMicroFrontendLister(f.Informer().GetIndexer())
}
