// Code generated by failery v1.0.0. DO NOT EDIT.

package disabled

import storage "github.com/kyma-project/kyma/components/ui-api-layer/internal/domain/content/storage"

// ContentGetter is an autogenerated failing mock type for the ContentGetter type
type ContentGetter struct {
	err error
}

// NewContentGetter creates a new ContentGetter type instance
func NewContentGetter(err error) *ContentGetter {
	return &ContentGetter{err: err}
}

// Find provides a failing mock function with given fields: kind, id
func (_m *ContentGetter) Find(kind string, id string) (*storage.Content, error) {
	var r0 *storage.Content
	var r1 error
	r1 = _m.err

	return r0, r1
}
