// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/kyma/components/compass-runtime-agent/internal/apperrors"
	applications "github.com/kyma-project/kyma/components/compass-runtime-agent/internal/kyma/applications"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/kyma/components/compass-runtime-agent/internal/kyma/model"

	types "k8s.io/apimachinery/pkg/types"
)

// CredentialsService is an autogenerated mock type for the CredentialsService type
type CredentialsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: application, appUID, packageID, credentials
func (_m *CredentialsService) Create(application string, appUID types.UID, packageID string, credentials *model.Credentials) (applications.Credentials, apperrors.AppError) {
	ret := _m.Called(application, appUID, packageID, credentials)

	var r0 applications.Credentials
	if rf, ok := ret.Get(0).(func(string, types.UID, string, *model.Credentials) applications.Credentials); ok {
		r0 = rf(application, appUID, packageID, credentials)
	} else {
		r0 = ret.Get(0).(applications.Credentials)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string, types.UID, string, *model.Credentials) apperrors.AppError); ok {
		r1 = rf(application, appUID, packageID, credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name
func (_m *CredentialsService) Delete(name string) apperrors.AppError {
	ret := _m.Called(name)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) apperrors.AppError); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Get provides a mock function with given fields: application, credentials
func (_m *CredentialsService) Get(application string, credentials applications.Credentials) (model.Credentials, apperrors.AppError) {
	ret := _m.Called(application, credentials)

	var r0 model.Credentials
	if rf, ok := ret.Get(0).(func(string, applications.Credentials) model.Credentials); ok {
		r0 = rf(application, credentials)
	} else {
		r0 = ret.Get(0).(model.Credentials)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string, applications.Credentials) apperrors.AppError); ok {
		r1 = rf(application, credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: application, appUID, packageID, credentials
func (_m *CredentialsService) Upsert(application string, appUID types.UID, packageID string, credentials *model.Credentials) (applications.Credentials, apperrors.AppError) {
	ret := _m.Called(application, appUID, packageID, credentials)

	var r0 applications.Credentials
	if rf, ok := ret.Get(0).(func(string, types.UID, string, *model.Credentials) applications.Credentials); ok {
		r0 = rf(application, appUID, packageID, credentials)
	} else {
		r0 = ret.Get(0).(applications.Credentials)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string, types.UID, string, *model.Credentials) apperrors.AppError); ok {
		r1 = rf(application, appUID, packageID, credentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}
