// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/kyma-project/kyma/components/telemetry-operator/apis/telemetry/v1alpha1"
)

// fileWriter is an autogenerated mock type for the fileWriter type
type fileWriter struct {
	mock.Mock
}

// preparePipelineDryRun provides a mock function with given fields: ctx, workDir, pipeline
func (_m *fileWriter) preparePipelineDryRun(ctx context.Context, workDir string, pipeline *v1alpha1.LogPipeline) (func(), error) {
	ret := _m.Called(ctx, workDir, pipeline)

	var r0 func()
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.LogPipeline) func()); ok {
		r0 = rf(ctx, workDir, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.LogPipeline) error); ok {
		r1 = rf(ctx, workDir, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewFileWriter interface {
	mock.TestingT
	Cleanup(func())
}

// newFileWriter creates a new instance of fileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newFileWriter(t mockConstructorTestingTnewFileWriter) *fileWriter {
	mock := &fileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
