// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// NsBrokerFacade is an autogenerated mock type for the NsBrokerFacade type
type NsBrokerFacade struct {
	mock.Mock
}

// Create provides a mock function with given fields: destinationNs
func (_m *NsBrokerFacade) Create(destinationNs string) error {
	ret := _m.Called(destinationNs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(destinationNs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: destinationNs
func (_m *NsBrokerFacade) Delete(destinationNs string) error {
	ret := _m.Called(destinationNs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(destinationNs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exist provides a mock function with given fields: destinationNs
func (_m *NsBrokerFacade) Exist(destinationNs string) (bool, error) {
	ret := _m.Called(destinationNs)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(destinationNs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(destinationNs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
