# .PHONY: ci-skr-gherkin
# ci-skr-gherkin:
# 	npm install
# 	./node_modules/.bin/cucumber-js features/skr-test/skr.feature

.PHONY: ci-certificate-gherkin
ci-skr-gherkin:
	npm install
	./node_modules/.bin/cucumber-js features/Ingress-certificate/certificate.feature