// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/kyma/components/application-gateway/pkg/apperrors"
	authorization "github.com/kyma-project/kyma/components/application-gateway/pkg/authorization"

	csrf "github.com/kyma-project/kyma/components/application-gateway/internal/csrf"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetTokenEndpointResponse provides a mock function with given fields: csrfEndpointURL, strategy
func (_m *Client) GetTokenEndpointResponse(csrfEndpointURL string, strategy authorization.Strategy) (*csrf.Response, apperrors.AppError) {
	ret := _m.Called(csrfEndpointURL, strategy)

	var r0 *csrf.Response
	if rf, ok := ret.Get(0).(func(string, authorization.Strategy) *csrf.Response); ok {
		r0 = rf(csrfEndpointURL, strategy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*csrf.Response)
		}
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string, authorization.Strategy) apperrors.AppError); ok {
		r1 = rf(csrfEndpointURL, strategy)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// InvalidateTokenCache provides a mock function with given fields: csrfEndpointURL
func (_m *Client) InvalidateTokenCache(csrfEndpointURL string) {
	_m.Called(csrfEndpointURL)
}
