// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"
import services "k8s.io/helm/pkg/proto/hapi/services"
import ybind "github.com/kyma-project/kyma/components/helm-broker/internal/ybind"
import internal "github.com/kyma-project/kyma/components/helm-broker/internal"

// BindTemplateRenderer is an autogenerated mock type for the BindTemplateRenderer type
type BindTemplateRenderer struct {
	mock.Mock
}

// Render provides a mock function with given fields: bindTemplate, resp
func (_m *BindTemplateRenderer) Render(bindTemplate internal.BundlePlanBindTemplate, resp *services.InstallReleaseResponse) (ybind.RenderedBindYAML, error) {
	ret := _m.Called(bindTemplate, resp)

	var r0 ybind.RenderedBindYAML
	if rf, ok := ret.Get(0).(func(internal.BundlePlanBindTemplate, *services.InstallReleaseResponse) ybind.RenderedBindYAML); ok {
		r0 = rf(bindTemplate, resp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ybind.RenderedBindYAML)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.BundlePlanBindTemplate, *services.InstallReleaseResponse) error); ok {
		r1 = rf(bindTemplate, resp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
