// Code generated by mockery v1.0.0
package automock

import chart "k8s.io/helm/pkg/proto/hapi/chart"
import internal "github.com/kyma-project/kyma/components/helm-broker/internal"
import mock "github.com/stretchr/testify/mock"
import semver "github.com/Masterminds/semver"

// chartStorage is an autogenerated mock type for the chartStorage type
type chartStorage struct {
	mock.Mock
}

// Get provides a mock function with given fields: ns, name, ver
func (_m *chartStorage) Get(ns internal.Namespace, name internal.ChartName, ver semver.Version) (*chart.Chart, error) {
	ret := _m.Called(ns, name, ver)

	var r0 *chart.Chart
	if rf, ok := ret.Get(0).(func(internal.Namespace, internal.ChartName, semver.Version) *chart.Chart); ok {
		r0 = rf(ns, name, ver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chart.Chart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.Namespace, internal.ChartName, semver.Version) error); ok {
		r1 = rf(ns, name, ver)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
