// Code generated by mockery v1.0.0
package automock

import internal "github.com/kyma-project/kyma/components/helm-broker/internal"
import mock "github.com/stretchr/testify/mock"

// InstanceBindDataGetter is an autogenerated mock type for the InstanceBindDataGetter type
type InstanceBindDataGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: iID
func (_m *InstanceBindDataGetter) Get(iID internal.InstanceID) (*internal.InstanceBindData, error) {
	ret := _m.Called(iID)

	var r0 *internal.InstanceBindData
	if rf, ok := ret.Get(0).(func(internal.InstanceID) *internal.InstanceBindData); ok {
		r0 = rf(iID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.InstanceBindData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.InstanceID) error); ok {
		r1 = rf(iID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
