// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kyma-project/kyma/components/application-broker/pkg/apis/applicationconnector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApplicationMappings implements ApplicationMappingInterface
type FakeApplicationMappings struct {
	Fake *FakeApplicationconnectorV1alpha1
	ns   string
}

var applicationmappingsResource = schema.GroupVersionResource{Group: "applicationconnector.kyma-project.io", Version: "v1alpha1", Resource: "applicationmappings"}

var applicationmappingsKind = schema.GroupVersionKind{Group: "applicationconnector.kyma-project.io", Version: "v1alpha1", Kind: "ApplicationMapping"}

// Get takes name of the applicationMapping, and returns the corresponding applicationMapping object, and an error if there is any.
func (c *FakeApplicationMappings) Get(name string, options v1.GetOptions) (result *v1alpha1.ApplicationMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(applicationmappingsResource, c.ns, name), &v1alpha1.ApplicationMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationMapping), err
}

// List takes label and field selectors, and returns the list of ApplicationMappings that match those selectors.
func (c *FakeApplicationMappings) List(opts v1.ListOptions) (result *v1alpha1.ApplicationMappingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(applicationmappingsResource, applicationmappingsKind, c.ns, opts), &v1alpha1.ApplicationMappingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ApplicationMappingList{ListMeta: obj.(*v1alpha1.ApplicationMappingList).ListMeta}
	for _, item := range obj.(*v1alpha1.ApplicationMappingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested applicationMappings.
func (c *FakeApplicationMappings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(applicationmappingsResource, c.ns, opts))

}

// Create takes the representation of a applicationMapping and creates it.  Returns the server's representation of the applicationMapping, and an error, if there is any.
func (c *FakeApplicationMappings) Create(applicationMapping *v1alpha1.ApplicationMapping) (result *v1alpha1.ApplicationMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(applicationmappingsResource, c.ns, applicationMapping), &v1alpha1.ApplicationMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationMapping), err
}

// Update takes the representation of a applicationMapping and updates it. Returns the server's representation of the applicationMapping, and an error, if there is any.
func (c *FakeApplicationMappings) Update(applicationMapping *v1alpha1.ApplicationMapping) (result *v1alpha1.ApplicationMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(applicationmappingsResource, c.ns, applicationMapping), &v1alpha1.ApplicationMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationMapping), err
}

// Delete takes name of the applicationMapping and deletes it. Returns an error if one occurs.
func (c *FakeApplicationMappings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(applicationmappingsResource, c.ns, name), &v1alpha1.ApplicationMapping{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApplicationMappings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(applicationmappingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ApplicationMappingList{})
	return err
}

// Patch applies the patch and returns the patched applicationMapping.
func (c *FakeApplicationMappings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ApplicationMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(applicationmappingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ApplicationMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationMapping), err
}
