// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import getter "github.com/kyma-project/kyma/components/helm-broker/internal/addon/provider"
import mock "github.com/stretchr/testify/mock"

// AddonGetterFactory is an autogenerated mock type for the AddonGetterFactory type
type AddonGetterFactory struct {
	mock.Mock
}

// NewGetter provides a mock function with given fields: rawURL, instPath
func (_m *AddonGetterFactory) NewGetter(rawURL string, instPath string) (getter.AddonClient, error) {
	ret := _m.Called(rawURL, instPath)

	var r0 getter.AddonClient
	if rf, ok := ret.Get(0).(func(string, string) getter.AddonClient); ok {
		r0 = rf(rawURL, instPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(getter.AddonClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(rawURL, instPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
