{
 "title": "Web APPs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "ui",
    "label": "UI",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\",label_kyma_grafana=\"enabled\",label_kyma_component=\"ui\"},label_app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service_name=~\"$ui\"}[1m])) by (le))",
     "legendFormat": "Histogram 50 Quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service_name=~\"$ui\"}[1m])) by (le))",
     "legendFormat": "Histogram 90 Quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service_name=~\"$ui\"}[1m])) by (le))",
     "legendFormat": "Histogram 99 Quantile"
    }
   ]
  },
  {
   "title": "Client Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service_name=~\"$ui\"}[1m])) by (le))",
     "legendFormat": "Histogram 50 Quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service_name=~\"$ui\"}[1m])) by (le))",
     "legendFormat": "Histogram 90 Quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service_name=~\"$ui\"}[1m])) by (le))",
     "legendFormat": "Histogram 99 Quantile"
    }
   ]
  },
  {
   "title": "Rate of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=\"$ui\"}[5m]))"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (2xx)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$ui\",response_code=~\"2.*\"}[15m])) / sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$ui\"}[15m]))*100"
    }
   ]
  },
  {
   "title": "Incoming Error Rates(5xx)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$ui\",response_code=~\"5.*\"}[5m])) / sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$ui\"}[5m]))"
    }
   ]
  },
  {
   "title": "Incoming Failure rate (4xx Errors)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$ui\",response_code=~\"4.*\"}[5m])) / sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$ui\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\",pod=~\"$ui.*\"}) by (created_by_kind)",
     "legendFormat": "Pod Count"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~\"$ui.*\", container_name!=\"POD\",container_name!=\"\"}/(1024*1024)",
     "legendFormat": "Usage: {{pod_name}}/{{container_name}})"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$ui.*\"}/(1024*1024)",
     "legendFormat": "Limit: {{pod}}/{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$ui.*\"}/(1024*1024)",
     "legendFormat": "Request: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$ui.*\"}/(1024*1024)",
     "legendFormat": "memory_cache: {{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$ui.*\"}/(1024*1024)",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_swap{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$ui.*\"}/(1024*1024)",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Fail Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_failcnt{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$ui.*\"}",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, container_name)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",image!=\"\",container_name!=\"POD\",pod_name=~\"$ui.*\"}[5m]))*1000",
     "legendFormat": "Usage:{{pod_name}}/{{container_name}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$ui.*\"}*1000",
     "legendFormat": "Requests: {{pod}}/{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$ui.*\"}*1000",
     "legendFormat": "Limits:{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "More CPU Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",container_name!=\"\",pod_name=~\"$ui.*\"}[5m])",
     "legendFormat": "cpu_cfs_throttled:{{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$ui.*\"}[5m])))/(1024*1024)",
     "legendFormat": "RX: {{pod_name}}"
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$ui.*\"}[5m])))/(1024*1024)",
     "legendFormat": "TX: {{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=~\"$ui.*\"}[5m])) by (pod_name,device)/(1024*1024)",
     "legendFormat": "Container FS Writes Bytes  (Pod: {{pod_name}})"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=~\"$ui.*\"}[5m])) by (pod_name,device)/(1024*1024)",
     "legendFormat": "Container FS Read Bytes  (Pod: {{pod_name}})"
    }
   ]
  }
 ]
}