// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	release "k8s.io/helm/pkg/proto/hapi/release"

	v1alpha1 "github.com/kyma-project/kyma/components/application-operator/pkg/apis/applicationconnector/v1alpha1"
)

// ReleaseManager is an autogenerated mock type for the ReleaseManager type
type ReleaseManager struct {
	mock.Mock
}

// CheckReleaseExistence provides a mock function with given fields: name
func (_m *ReleaseManager) CheckReleaseExistence(name string) (bool, error) {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckReleaseStatus provides a mock function with given fields: name
func (_m *ReleaseManager) CheckReleaseStatus(name string) (release.Status_Code, string, error) {
	ret := _m.Called(name)

	var r0 release.Status_Code
	if rf, ok := ret.Get(0).(func(string) release.Status_Code); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(release.Status_Code)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteReleaseIfExists provides a mock function with given fields: name
func (_m *ReleaseManager) DeleteReleaseIfExists(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstallChart provides a mock function with given fields: _a0
func (_m *ReleaseManager) InstallChart(_a0 *v1alpha1.Application) (release.Status_Code, string, error) {
	ret := _m.Called(_a0)

	var r0 release.Status_Code
	if rf, ok := ret.Get(0).(func(*v1alpha1.Application) release.Status_Code); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(release.Status_Code)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(*v1alpha1.Application) string); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*v1alpha1.Application) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpgradeReleases provides a mock function with given fields:
func (_m *ReleaseManager) UpgradeReleases() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
