// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import registered "github.com/kyma-project/kyma/components/event-service/internal/events/registered"

// EventsClient is an autogenerated mock type for the EventsClient type
type EventsClient struct {
	mock.Mock
}

// GetActiveEvents provides a mock function with given fields: appName
func (_m *EventsClient) GetActiveEvents(appName string) (registered.ActiveEvents, error) {
	ret := _m.Called(appName)

	var r0 registered.ActiveEvents
	if rf, ok := ret.Get(0).(func(string) registered.ActiveEvents); ok {
		r0 = rf(appName)
	} else {
		r0 = ret.Get(0).(registered.ActiveEvents)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(appName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
