{
 "title": "Compass",
 "description": "Compass components",
 "tags": [
  "kyma",
  "compass"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Director - Technical metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"compass-director-[^(tenant)].*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "Current: {{`{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"compass-director-[^(tenant)].*\"}",
     "legendFormat": "Requests: {{`{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"compass-director-[^(tenant)].*\"}",
     "legendFormat": "Limit: {{`{container}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"compass-director-[^(tenant)].*\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "Current: {{`{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"compass-director-[^(tenant)].*\"}",
     "legendFormat": "Requests: {{`{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"compass-director-[^(tenant)].*\"}",
     "legendFormat": "Limit: {{`{container}}`}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"compass-director-[^(tenant)].*\"}[1m])))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  { "title": "Director - Business metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}