apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: eu.gcr.io/kyma-project/external/istio
  tag: {{ .Chart.Version }}
  profile: default
  components:
    egressGateways:
    - enabled: false
      k8s:
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-egressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 120Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          - resource:
              name: memory
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 0
        securityContext:
{{- toYaml .Values.istio.securityContext | nindent 14 }}
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
        env:
        - name: PILOT_HTTP10
          value: "1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 5
        hpaSpec:
          maxReplicas: 5
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 512Mi
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
        securityContext:
{{- toYaml .Values.istio.securityContext | nindent 14 }}
  meshConfig:
    accessLogFile: /dev/stdout
    trustDomain: cluster.local
    defaultConfig:
      proxyMetadata: {}
      tracing:
        # sampling: 1 # use the istio default (which is 1) to support override by pilot env variable at runtime
        zipkin:
          address: "{{ .Values.global.tracing.zipkinAddress }}"
    enablePrometheusMerge: false
    enableTracing: {{ .Values.global.tracing.enabled }}
  values:
    global:
      imagePullPolicy: IfNotPresent
      istioNamespace: istio-system
      pilotCertProvider: istiod
      priorityClassName: "{{ .Values.global.priorityClassName }}"
      proxy:
        holdApplicationUntilProxyStarts: true
        readinessFailureThreshold: 40
        readinessInitialDelaySeconds: 5
        readinessPeriodSeconds: 5
        resources:
          requests:
            cpu: 75m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
      proxy_init:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
      objectSelector:
        autoInject: true
        enabled: false
      rewriteAppHTTPProbe: true
