{
 "title": "Application-Registry",
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": "label_values(application_registry_endpoints_duration ,exported_endpoint)"
   }
  ]
 },
 "panels": [
  { "title": "Resources and Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kyma-integration\",pod_name=~\"application-registry.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kyma-integration\",pod_name=~\"application-registry.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"kyma-integration\",pod_name=~\"application-registry.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"kyma-integration\",pod_name=~\"application-registry.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"application-registry\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"application-registry\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"application-registry\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"application-registry\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"application-registry\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  { "title": "Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "99.5%ile of request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "application_registry_endpoints_duration{exported_endpoint=~\"$endpoint\", quantile=\"0.995\"}",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  { "title": "Response Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Codes: $endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(application_registry_endpoints_responses{exported_endpoint=~\"$endpoint\"}[10m])",
     "legendFormat": "{{exported_endpoint}} {{ status }}"
    }
   ]
  }
 ]
}