{
 "title": "Event Mesh / Pods",
 "tags": [
  "kyma",
  "eventing"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(kube_pod_info{pod=~\"default-broker-ingress.*\"} or kube_pod_info{pod=~\"application-broker.*\"} or kube_pod_info{pod=~\"eventing-controller.*\"} or kube_pod_info{pod=~\"autoscaler.*\"} or kube_pod_info{pod=~\"application-connector.*\"})"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(kube_pod_labels{label_app=~\".*connectivity-validator\", namespace=~\"$namespace\"}, label_release)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container, pod) (container_memory_usage_bytes{job=\"kubelet\", container!=\"POD\", container !=\"\"}) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sum by(container, pod) (container_memory_usage_bytes{job=\"kubelet\", container!=\"POD\", container !=\"\"}) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Current: {{`{{ pod }}`}}({{`{{ container }}`}})"
    },
    {
     "expr": "sum by(container, pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sum by(container, pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Requested: {{`{{ pod }}`}}({{`{{ container }}`}})"
    },
    {
     "expr": "sum by(container, pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sum by(container, pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Limit: {{`{{ pod }}`}}({{`{{ container }}`}})"
    },
    {
     "expr": "sum by(container, pod) (container_memory_cache{job=\"kubelet\", container!=\"POD\", container!=\"\"}) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sum by(container, pod) (container_memory_cache{job=\"kubelet\", container!=\"POD\", container!=\"\"}) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Cache: {{`{{ pod }}`}}({{`{{ container }}`}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, pod_name) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container!=\"POD\"}[4m])) * on(pod_name) group_left()\nlabel_replace(max(kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"}) by (pod), \"pod_name\", \"$1\", \"pod\", \"(.*)\") or sum by (container, pod_name) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container!=\"POD\"}[4m])) * on(pod_name) group_left()\nlabel_replace(max(kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}) by (pod), \"pod_name\", \"$1\", \"pod\", \"(.*)\")",
     "legendFormat": "Current: {{`{{ pod_name }}`}}({{`{{ container }}`}})"
    },
    {
     "expr": "sum by (container, pod) (irate(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}[4m])) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sum by (container, pod) (irate(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}[4m])) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Requested: {{`{{ pod }}`}}({{`{{ container }}`}})"
    },
    {
     "expr": "sum by (container, pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"}) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sum by (container, pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"}) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Limit: {{`{{ pod }}`}}({{`{{ container }}`}})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\"}[4m])))\n* on(pod)\nkube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\"}[4m])))\n* on(pod)\nkube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "RX: {{`{{ pod }}`}}"
    },
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\"}[4m])))\n* on(pod)\nkube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\"}[4m])))\n* on(pod)\nkube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "TX: {{`{{ pod }}`}}"
    }
   ]
  },
  {
   "title": "Total Restarts Per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container, pod) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\"}) * on(pod) group_left() kube_pod_labels{label_kyma_project_io_dashboard=\"event-mesh\", label_app=~\"$app.*\", namespace=\"$namespace\"} or max by (container, pod) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\"}) * on(pod) group_left() kube_pod_labels{label_eventing_knative_dev_broker=\"default\", namespace=\"$namespace\"}",
     "legendFormat": "Restarts: {{`{{ pod }}`}}({{`{{ container }}`}})"
    }
   ]
  }
 ]
}