{
 "title": "Event Bus Subscription",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kyma_subscription_namespace",
    "label": "Namespace",
    "query": "label_values(eventbus_controller_kyma_subscription_status, subscription_ns)"
   },
   {
    "name": "kyma_subscription_name",
    "label": "Kyma Subscription Name",
    "query": "label_values(eventbus_controller_kyma_subscription_status{subscription_ns=\"$kyma_subscription_namespace\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kyma Subscription Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "NOT READY / READY" }
   ],
   "targets": [
    {
     "expr": "eventbus_controller_kyma_subscription_status{subscription_ns=~\"$kyma_subscription_namespace\",name=~\"$kyma_subscription_name\"}"
    }
   ]
  },
  {
   "title": "Knative Subscription Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "NOT READY / READY" }
   ],
   "targets": [
    {
     "expr": "eventbus_controller_knative_subscription_status{subscription_ns=~\"$kyma_subscription_namespace\", name=~\"$kyma_subscription_name\"}"
    }
   ]
  },
  {
   "title": "Knative Channels Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "NOT READY / READY" }
   ],
   "targets": [
    {
     "expr": "eventbus_controller_knative_channel_status{name=~\"$kyma_subscription_name\"}"
    }
   ]
  }
 ]
}