{
 "title": "Event Mesh / Delivery",
 "tags": [
  "kyma",
  "eventing"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(kube_pod_info{pod=~\"default-broker-ingress.*\"} or kube_pod_info{pod=~\"application-broker.*\"})"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(kube_pod_labels{label_app=~\".*connectivity-validator\",}, label_release)"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Connectivity Validator Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(destination_service) (rate(istio_requests_total{destination_service=~\"$app-validator.kyma-integration.svc.cluster.local\", response_code=~\"2.*\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum by(destination_service) (rate(istio_requests_total{destination_service=~\"$app-validator.kyma-integration.svc.cluster.local\", response_code=~\"4.*\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum by(destination_service) (rate(istio_requests_total{destination_service=~\"$app-validator.kyma-integration.svc.cluster.local\", response_code=~\"5.*\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "HTTP Adapter Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(revision_app_request_count{configuration_name=\"$app\",container_name=\"queue-proxy\",namespace_name=\"kyma-integration\",response_code_class=\"2xx\",revision_name=~\"$app-.*\",service_name=~\"$app\"}[5m])",
     "legendFormat": "2XX"
    },
    {
     "expr": "rate(revision_app_request_count{configuration_name=\"$app\",container_name=\"queue-proxy\",namespace_name=\"kyma-integration\",response_code_class=\"4xx\",revision_name=~\"$app-.*\",service_name=~\"$app\"}[5m])",
     "legendFormat": "4XX"
    },
    {
     "expr": "rate(revision_app_request_count{configuration_name=\"$app\",container_name=\"queue-proxy\",namespace_name=\"kyma-integration\",response_code_class=\"5xx\",revision_name=~\"$app-.*\",service_name=~\"$app\"}[5m])",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Broker Ingress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(event_type)(rate(broker_ingress_event_count{event_source=\"$app\",name=\"default\",namespace_name=\"$namespace\",response_code=\"202\",response_code_class=\"2xx\"}[5m]))",
     "legendFormat": "2XX ({{`{{ event_type }}`}})"
    },
    {
     "expr": "sum by(event_type)(rate(broker_ingress_event_count{event_source=\"$app\",name=\"default\",namespace_name=\"$namespace\",response_code=\"202\",response_code_class=\"4xx\"}[5m]))",
     "legendFormat": "4XX ({{`{{ event_type }}`}})"
    },
    {
     "expr": "sum by(event_type)(rate(broker_ingress_event_count{event_source=\"$app\",name=\"default\",namespace_name=\"$namespace\",response_code=\"202\",response_code_class=\"5xx\"}[5m]))",
     "legendFormat": "5XX ({{`{{ event_type }}`}})"
    }
   ]
  },
  {
   "title": "Broker Filter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(filter_type)(rate(broker_filter_event_count{filter_source=\"$app\",broker_name=\"default\",namespace_name=\"$namespace\",response_code_class=\"2xx\"}[5m]))",
     "legendFormat": "2XX ({{`{{ filter_type }}`}})"
    },
    {
     "expr": "sum by(filter_type)(rate(broker_filter_event_count{filter_source=\"$app\",broker_name=\"default\",namespace_name=\"$namespace\",response_code_class=\"4xx\"}[5m]))",
     "legendFormat": "4XX ({{`{{ filter_type }}`}})"
    },
    {
     "expr": "sum by(filter_type)(rate(broker_filter_event_count{filter_source=\"$app\",broker_name=\"default\",namespace_name=\"$namespace\",response_code_class=\"5xx\"}[5m]))",
     "legendFormat": "5XX ({{`{{ filter_type }}`}})"
    }
   ]
  }
 ]
}