{
 "title": "Helm Broker",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC duration [s] - Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"helm-broker-metrics\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "GC duration [s] - Controller",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"addon-controller-metrics\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"helm-broker-metrics\"}",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "process_open_fds{service=\"helm-broker-etcd-stateful-client\"}",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "process_open_fds{service=\"addon-controller-metrics\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"helm-broker-metrics\"}",
     "legendFormat": "{{pod}} (Broker)"
    },
    {
     "expr": "go_threads{service=\"addon-controller-metrics\"}",
     "legendFormat": "{{pod}} (Controller)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"helm-broker-metrics\"}",
     "legendFormat": "{{pod}} (Broker)"
    },
    {
     "expr": "go_goroutines{service=\"addon-controller-metrics\"}",
     "legendFormat": "{{pod}} (Controller)"
    }
   ]
  },
  {
   "title": "Go memstats - Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"helm-broker-metrics\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"helm-broker-metrics\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"helm-broker-metrics\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"helm-broker-metrics\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Go memstats - Controller",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"addon-controller-metrics\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"addon-controller-metrics\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"addon-controller-metrics\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"addon-controller-metrics\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"helm-broker.*\"}[2m]))",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"helm-broker.*\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"helm-broker.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"helm-broker.*\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"helm-broker.*\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"helm-broker.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"helm-broker.*\"}[2m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}