{
 "title": "Kyma / Lambda",
 "tags": [
  "serverless",
  "kyma"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels,namespace)"
   },
   {
    "name": "lambda_service",
    "label": "Lambda",
    "query": "label_values(kube_service_labels{label_created_by=\"kubeless\",namespace=\"$environment\"},service)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ratio of Requests per Response Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\",response_code=~\"2.*\"}[2m])) by (destination_service_name, response_code) / sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\",}[2m])) by (destination_service_name, response_code)",
     "legendFormat": "2xx response code"
    },
    {
     "expr": "sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\",response_code=~\"5.*\"}[2m])) by (destination_service_name, response_code) / sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, response_code)",
     "legendFormat": "5xx response code"
    },
    {
     "expr": "sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\",response_code=~\"4.*\"}[2m])) by (destination_service_name, response_code) / sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, response_code)",
     "legendFormat": "4xx response code"
    }
   ]
  },
  {
   "title": "Request Duration (95th)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(max(container_memory_usage_bytes{pod_name=~\"$lambda_service.*\", container_name=\"$lambda_service\", container_name!=\"POD\"}) / max (kube_pod_container_resource_limits_memory_bytes{pod=~\"$lambda_service.*\", container=\"$lambda_service\"})) * 100",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (rate(container_cpu_usage_seconds_total{container_name=\"$lambda_service\", pod_name=~\"$lambda_service.*\", namespace=\"$environment\"}[2m])  )",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Success Rate (Ratio of 2xx Responses)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\", response_code=~\"2.*\"}[2m])) / sum(rate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) ",
     "legendFormat": "2xx rate"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"$lambda_service\",namespace=\"$environment\"}",
     "legendFormat": "Replicas"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Requests per Second by Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service, response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Response Time per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$environment\", destination_service_name=\"$lambda_service\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"$environment\", pod=~\"$lambda_service.*\", container=\"$lambda_service\", container!=\"POD\"})",
     "legendFormat": "Current {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"$environment\", resource=\"memory\", pod=~\"$lambda_service.*\", container=\"$lambda_service\"})",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"$lambda_service\", pod_name=~\"$lambda_service.*\", namespace=\"$environment\"}[2m])",
     "legendFormat": "Current {{pod_name}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"$environment\", resource=\"cpu\", pod=~\"$lambda_service.*\", container=\"$lambda_service\"})",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"$lambda_service\",namespace=\"$environment\"}",
     "legendFormat": "Replicas"
    }
   ]
  }
 ]
}