{
 "title": "ORY Oathkeeper-maester",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC invocations durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "quantile: {{ quantile }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "Heap in use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "Stack in use"
    },
    {
     "expr": "container_memory_usage_bytes{container_name=~\"oathkeeper-maester|istio-proxy\", pod_name=~\"ory-oathkeeper-maester.*\"}",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container_name=~\"oathkeeper-maester|istio-proxy\", pod_name=~\"ory-oathkeeper-maester.*\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}