{
 "title": "Kyma / Services",
 "description": "Dashboard for REST Services",
 "tags": [ "kyma" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\",label_kyma_grafana=\"enabled\"},label_app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=\"$service\"}[5m]))",
     "legendFormat": "Rate of requests"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(istio_request_duration_milliseconds_bucket{source_workload=~\"$service\", source_workload_namespace=~\"$namespace\"}[5m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{source_workload=~\"$service\", source_workload_namespace=~\"$namespace\"}[5m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{source_workload=~\"$service\", source_workload_namespace=~\"$namespace\"}[5m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (HTTP non-5xx responses)",
   "type": "singlestat",
   "description": "red val <= 10\nyellow val >10 <=50\ngreen val >50",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$service\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$service\",response_code=~\"4.*\"}[5m])) / sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$service\",response_code=~\"5.*\"}[5m])) / sum(irate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\",pod=~\"$service.*\"}) by (created_by_kind)",
     "legendFormat": "Pod count"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~\"$service.*\", container_name!=\"POD\",container_name!=\"\"}/(1024*1024)",
     "legendFormat": "Usage: {{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$service.*\"}/(1024*1024)",
     "legendFormat": "Limit: {{`{{pod}}`}}/{{`{{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$service.*\"}/(1024*1024)",
     "legendFormat": "Request:{{`{{pod}}`}}/{{`{{container}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, container_name)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",image!=\"\",container_name!=\"POD\",pod_name=~\"$service.*\"}[5m]))*1000",
     "legendFormat": "Usage:{{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$service.*\"}*1000",
     "legendFormat": "Request:{{`{{pod}}`}}/{{`{{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$service.*\"}*1000",
     "legendFormat": "Limit:{{`{{pod}}`}}/{{`{{container}}`}}"
    }
   ]
  },
  {
   "title": "More CPU Stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",container_name!=\"\",pod_name=~\"demo-service.*\"}[5m])",
     "legendFormat": "cpu_cfs_throttled:{{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$service.*\"}[5m])))/(1024*1024)",
     "legendFormat": "RX:{{`{{pod_name}}`}}"
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$service.*\"}[5m])))/(1024*1024)",
     "legendFormat": "TX:{{`{{pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=~\"$service.*\"}[5m])) by (pod_name,device)/(1024*1024)",
     "legendFormat": "Writes:{{`{{pod_name}}`}}/{{`{{container_name}}`}}({{`{{device}}`}})"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=~\"$service.*\"}[5m])) by (pod_name,device)/(1024*1024)",
     "legendFormat": "Reads:{{`{{pod_name}}`}}/{{`{{container_name}}`}}({{`{{device}}`}})"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "graph",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$service.*\"}/(1024*1024)",
     "legendFormat": "memory_cache:{{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$service.*\"}/(1024*1024)",
     "legendFormat": "{{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "graph",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_swap{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$service.*\"}/(1024*1024)",
     "legendFormat": "{{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    }
   ]
  },
  {
   "title": "Memory Failcnt",
   "type": "graph",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_failcnt{namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\",pod_name=~\"$service.*\"}",
     "legendFormat": "{{`{{pod_name}}`}}/{{`{{container_name}}`}}"
    }
   ]
  }
 ]
}