FROM node:6

RUN apt-get update &&  apt-get install git

ADD package.json kubeless_rt/
ADD lib/helper.js kubeless_rt/lib/
ADD kubeless.js kubeless_rt/
ADD kubeless-npm-install.sh /
ADD start.sh /

WORKDIR kubeless_rt/

RUN npm install

RUN chmod +x /start.sh

USER 1000

ENTRYPOINT ["/start.sh"]
