// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/kyma/components/central-application-gateway/pkg/apperrors"

	clientcert "github.com/kyma-project/kyma/components/central-application-gateway/pkg/authorization/clientcert"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Strategy is an autogenerated mock type for the Strategy type
type Strategy struct {
	mock.Mock
}

// AddAuthorization provides a mock function with given fields: r, setter
func (_m *Strategy) AddAuthorization(r *http.Request, setter clientcert.SetClientCertificateFunc) apperrors.AppError {
	ret := _m.Called(r, setter)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(*http.Request, clientcert.SetClientCertificateFunc) apperrors.AppError); ok {
		r0 = rf(r, setter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Invalidate provides a mock function with given fields:
func (_m *Strategy) Invalidate() {
	_m.Called()
}
