// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ServiceBindingUsageListerExpansion allows custom methods to be added to
// ServiceBindingUsageLister.
type ServiceBindingUsageListerExpansion interface{}

// ServiceBindingUsageNamespaceListerExpansion allows custom methods to be added to
// ServiceBindingUsageNamespaceLister.
type ServiceBindingUsageNamespaceListerExpansion interface{}
