// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	applications "github.com/kyma-project/kyma/components/central-application-gateway/internal/metadata/applications"
	apperrors "github.com/kyma-project/kyma/components/central-application-gateway/pkg/apperrors"

	mock "github.com/stretchr/testify/mock"
)

// ServiceRepository is an autogenerated mock type for the ServiceRepository type
type ServiceRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: appName, serviceName, apiName
func (_m *ServiceRepository) Get(appName string, serviceName string, apiName string) (applications.Service, apperrors.AppError) {
	ret := _m.Called(appName, serviceName, apiName)

	var r0 applications.Service
	if rf, ok := ret.Get(0).(func(string, string, string) applications.Service); ok {
		r0 = rf(appName, serviceName, apiName)
	} else {
		r0 = ret.Get(0).(applications.Service)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string, string, string) apperrors.AppError); ok {
		r1 = rf(appName, serviceName, apiName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}
