APP_NAME = kubeless-tests
APP_PATH = tests/kubeless
BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-golang:go1.12
SCRIPTS_DIR = ../../common/makefiles
ENTRYPOINT = kubeless-tests.go
# COMPONENT_DIR is a local path to commponent
include $(SCRIPTS_DIR)/generic-make-go.mk


test: ;

