{
 "title": "Kyma / Event Mesh / Broker-Trigger",
 "tags": [
  "kyma",
  "eventing"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(broker_ingress_event_count{namespace_name!=\"unknown\"}, namespace_name)"
   }
  ]
 },
 "panels": [
  { "title": "Broker (broker-ingress)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(broker_ingress_event_count{namespace_name=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate  (2xx Event)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(broker_ingress_event_count{response_code_class=\"2xx\", namespace_name=~\"$namespace\"}[1m])) / sum(rate(broker_ingress_event_count{namespace_name=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Event Count by Event Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(broker_ingress_event_count{namespace_name=~\"$namespace\"}[1m])) by (event_type)",
     "legendFormat": "{{`{{event_type}}`}}"
    }
   ]
  },
  {
   "title": "Event Count by Event Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(broker_ingress_event_count{namespace_name=~\"$namespace\"}[1m])) by (event_source)",
     "legendFormat": "{{`{{event_source}}`}}"
    }
   ]
  },
  {
   "title": "Failure Rate (non-2xx Event)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(broker_ingress_event_count{response_code_class!=\"2xx\", namespace_name=~\"$namespace\"}[1m])) / sum(rate(broker_ingress_event_count{namespace_name=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Event Count by Response Code Class",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(broker_ingress_event_count{namespace_name=~\"$namespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{`{{response_code_class}}`}}"
    }
   ]
  },
  {
   "title": "Event Dispatch Latency ",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(broker_ingress_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Trigger (broker-filter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Event Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(broker_filter_event_count{namespace_name=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate  (2xx Event)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(broker_filter_event_count{response_code_class=\"2xx\", namespace_name=~\"$namespace\"}[1m])) / sum(rate(broker_filter_event_count{namespace_name=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Event Count by Response Code Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(broker_filter_event_count{namespace_name=~\"$namespace\", response_code!=\"417\"}[1m])) by (response_code_class)",
     "legendFormat": "{{`{{response_code_class}}`}}"
    }
   ]
  },
  {
   "title": "Failure Rate (non-2xx Event)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(broker_filter_event_count{response_code_class!=\"2xx\", response_code!=\"417\", namespace_name=~\"$namespace\"}[1m])) / sum(rate(broker_filter_event_count{namespace_name=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Event Dispatch Latency ",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(broker_filter_event_dispatch_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Event Processing Latency ",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(broker_filter_event_processing_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(broker_filter_event_processing_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(broker_filter_event_processing_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(broker_filter_event_processing_latencies_bucket{namespace_name=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}