// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import connectorservice "github.com/kyma-project/kyma/components/connectivity-certs-controller/internal/connectorservice"
import mock "github.com/stretchr/testify/mock"

// MutualTLSClientProvider is an autogenerated mock type for the MutualTLSClientProvider type
type MutualTLSClientProvider struct {
	mock.Mock
}

// CreateClient provides a mock function with given fields: credentials
func (_m *MutualTLSClientProvider) CreateClient(credentials connectorservice.CertificateCredentials) connectorservice.MutualTLSConnectorClient {
	ret := _m.Called(credentials)

	var r0 connectorservice.MutualTLSConnectorClient
	if rf, ok := ret.Get(0).(func(connectorservice.CertificateCredentials) connectorservice.MutualTLSConnectorClient); ok {
		r0 = rf(credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(connectorservice.MutualTLSConnectorClient)
		}
	}

	return r0
}
