// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha2 "github.com/kyma-project/kyma/components/application-registry/pkg/apis/istio/v1alpha2"
)

// AuthorizationPolicyInterface is an autogenerated mock type for the AuthorizationPolicyInterface type
type AuthorizationPolicyInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: policy
func (_m *AuthorizationPolicyInterface) Create(policy *v1alpha2.AuthorizationPolicy) (*v1alpha2.AuthorizationPolicy, error) {
	ret := _m.Called(policy)

	var r0 *v1alpha2.AuthorizationPolicy
	if rf, ok := ret.Get(0).(func(*v1alpha2.AuthorizationPolicy) *v1alpha2.AuthorizationPolicy); ok {
		r0 = rf(policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha2.AuthorizationPolicy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1alpha2.AuthorizationPolicy) error); ok {
		r1 = rf(policy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name, options
func (_m *AuthorizationPolicyInterface) Delete(name string, options *v1.DeleteOptions) error {
	ret := _m.Called(name, options)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.DeleteOptions) error); ok {
		r0 = rf(name, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
