// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/kyma-project/kyma/components/application-connector/pkg/client/clientset/versioned/typed/istio/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIstioV1alpha2 struct {
	*testing.Fake
}

func (c *FakeIstioV1alpha2) Checknothings(namespace string) v1alpha2.ChecknothingInterface {
	return &FakeChecknothings{c, namespace}
}

func (c *FakeIstioV1alpha2) Deniers(namespace string) v1alpha2.DenierInterface {
	return &FakeDeniers{c, namespace}
}

func (c *FakeIstioV1alpha2) Rules(namespace string) v1alpha2.RuleInterface {
	return &FakeRules{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIstioV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
