BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-golang:go1.12
SCRIPTS_DIR = ../../../common/makefiles
APP_PATH = tests/end-to-end/backup-restore-test
APP_NAME = backup-test
# COMPONENT_DIR is a local path to component
include $(SCRIPTS_DIR)/generic-make-go.mk

test: ;

