{
 "title": "Kyma / Rafter /  Controller Manager / Minio",
 "description": "minio dashboard",
 "tags": [
  "assets",
  "kyma"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": "rafter-minio" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server. In Kyma it is used as a dependency for the Rafter component. For more information, check out the docs.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "content": "<img src=\"https://www.dropbox.com/s/s5z6rn7offp7ov3/Minio_Logo_White.png?raw=1\" style=\"height: 55px;\"></img>\n<img src=\"https://www.dropbox.com/s/59wm2aemin3cvsc/Minio_wm_light_32px.png?raw=1\" style=\"height: 40px;\"></img>\n<p style=\"margin-top: 10px;\"><small>\nMinio is a high performance distributed object storage server. In Kyma it is used as a dependency for the Rafter component. For more information, check out the <a href=\"https://kyma-project.io/docs/components/rafter\">docs</a>.\n</small></p>"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the Minio server",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the Minio server"
    }
   ]
  },
  {
   "title": "Data Transmited",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_sent_bytes_total{service=\"$service\"}[1m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{service=\"$service\"}[1m])",
     "legendFormat": "Received:"
    }
   ]
  },
  {
   "title": "Total In/Out Throughput",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{service=\"$service\"}[1m])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(minio_network_sent_bytes_total{service=\"$service\"}[1m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "HTTP Requests duration/s",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"GET\",service=\"$service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"POST\",service=\"$service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"PUT\",service=\"$service\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"HEAD\",service=\"$service\"}[1m])",
     "legendFormat": "HEAD"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"DELETE\",service=\"$service\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Goroutines Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_goroutines{service=\"$service\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines Number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"$service\"}"
    }
   ]
  }
 ]
}