APP_NAME = nats-init
SCRIPTS_DIR = $(realpath $(shell pwd)/../..)/common/makefiles

include $(SCRIPTS_DIR)/docker.mk

.PHONY: path-to-referenced-charts
path-to-referenced-charts:
	@echo "resources/nats-streaming"

