// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"
import summary "github.com/kyma-project/kyma/tools/stability-checker/internal/summary"

// LogProcessor is an autogenerated mock type for the LogProcessor type
type LogProcessor struct {
	mock.Mock
}

// GetResults provides a mock function with given fields:
func (_m *LogProcessor) GetResults() []summary.SpecificTestStats {
	ret := _m.Called()

	var r0 []summary.SpecificTestStats
	if rf, ok := ret.Get(0).(func() []summary.SpecificTestStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]summary.SpecificTestStats)
		}
	}

	return r0
}

// Process provides a mock function with given fields: _a0
func (_m *LogProcessor) Process(_a0 []byte) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
