// Code generated by mockery v1.0.0
package automock

import internal "github.com/kyma-project/kyma/components/remote-environment-broker/internal"
import mock "github.com/stretchr/testify/mock"
import v2 "github.com/pmorie/go-open-service-broker-client/v2"

// converter is an autogenerated mock type for the converter type
type Converter struct {
	mock.Mock
}

// Convert provides a mock function with given fields: name, source, svc
func (_m *Converter) Convert(name internal.RemoteEnvironmentName, source internal.Source, svc internal.Service) (v2.Service, error) {
	ret := _m.Called(name, source, svc)

	var r0 v2.Service
	if rf, ok := ret.Get(0).(func(internal.RemoteEnvironmentName, internal.Source, internal.Service) v2.Service); ok {
		r0 = rf(name, source, svc)
	} else {
		r0 = ret.Get(0).(v2.Service)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.RemoteEnvironmentName, internal.Source, internal.Service) error); ok {
		r1 = rf(name, source, svc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
