// Code generated by mockery v1.0.0
package automock

import chart "k8s.io/helm/pkg/proto/hapi/chart"
import internal "github.com/kyma-project/kyma/components/helm-broker/internal"
import io "io"
import mock "github.com/stretchr/testify/mock"

// AddonLoader is an autogenerated mock type for the AddonLoader type
type AddonLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0
func (_m *AddonLoader) Load(_a0 io.Reader) (*internal.Addon, []*chart.Chart, error) {
	ret := _m.Called(_a0)

	var r0 *internal.Addon
	if rf, ok := ret.Get(0).(func(io.Reader) *internal.Addon); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Addon)
		}
	}

	var r1 []*chart.Chart
	if rf, ok := ret.Get(1).(func(io.Reader) []*chart.Chart); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*chart.Chart)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(io.Reader) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
