#!/usr/bin/env groovy
def label = "kyma-${UUID.randomUUID().toString()}"
def application = 'installer'
def dockerPushRoot = "${env.DOCKER_REGISTRY}${params.PUSH_DIR}"
def dockerImageTag = params.APP_VERSION

def gitCommitHash = ""

echo """
********************************
Job started with the following parameters:
DOCKER_REGISTRY=${env.DOCKER_REGISTRY}
PUSH_DIR=${params.PUSH_DIR}
DOCKER_CREDENTIALS=${env.DOCKER_CREDENTIALS}
GIT_REVISION=${params.GIT_REVISION}
GIT_BRANCH=${params.GIT_BRANCH}
APP_VERSION=${params.APP_VERSION}
APP_FOLDER=${env.APP_FOLDER}
FULL_BUILD=${params.FULL_BUILD}
********************************
"""

podTemplate(label: label) {
    node(label) {
        try {
            timestamps {
                timeout(time:20, unit:"MINUTES") {
                    ansiColor('xterm') {
                        stage("setup") {
                            checkout scm

                            gitCommitHash = sh(returnStdout: true, script: "bash $env.APP_FOLDER/scripts/extract-commit-hash.sh")

                            if(dockerImageTag == ""){
                                error("No version for docker tag defined, please set APP_VERSION parameter for master branch or GIT_BRANCH parameter for any branch")
                            }

                            withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS, passwordVariable: 'pwd', usernameVariable: 'uname')]) {
                                sh "docker login -u $uname -p '$pwd' $env.DOCKER_REGISTRY"
                            }
                        }

                        stage("install dependencies $application") {
                            execute("make resolve")
                        }

                        stage("code quality $application") {
                            execute("gometalinter --vendor --deadline=2m --disable-all --enable=vet --skip=pkg/client/clientset/versioned/fake ./...")
                        }

                        stage("build $application") {
                            execute("CGO_ENABLED=0 go build -ldflags \"-X main.gitCommitHash=${gitCommitHash}\" -o installer cmd/operator/main.go")
                        }

                        stage("test $application") {
                            execute("make test-report")
                            junit '**/unit-tests.xml'
                        }

                        if (params.FULL_BUILD) {
                            stage("IP scan $application (Sourceclear)"){
                                withCredentials([string(credentialsId: 'SRCCLR_API_TOKEN', variable: 'SRCCLR_API_TOKEN')]) {
                                    execute("make scan","SRCCLR_API_TOKEN=$SRCCLR_API_TOKEN")
                                }
                            }
                        }

                        stage("build image $application") {
                            dir(env.APP_FOLDER){
                                sh "pwd"
                                sh "ls -al"
                                sh "ls -al .."
                                sh "ls -al ../.."
                                sh "cp ./$application deploy/installer/$application"
                                sh "docker build -t ${dockerPushRoot}${application}:latest deploy/installer --label version=${dockerImageTag} --label component=${application}"
                            }
                        }

                        stage("push image") {
                            sh "docker tag ${dockerPushRoot}${application}:latest ${dockerPushRoot}${application}:${dockerImageTag}"
                            sh "docker push ${dockerPushRoot}${application}:${dockerImageTag}"
                            if (params.GIT_BRANCH == 'master') {
                                sh "docker push ${dockerPushRoot}${application}:latest"
                            }
                        }
                    }
                }
            }
        } catch (ex) {
            echo "Got exception: ${ex}"
            currentBuild.result = "FAILURE"
            def body = "${currentBuild.currentResult} ${env.JOB_NAME}${env.BUILD_DISPLAY_NAME}: on branch: ${params.GIT_BRANCH}. See details: ${env.BUILD_URL}"
            emailext body: body, recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'CulpritsRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: "${currentBuild.currentResult}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
        }
    }
}

def execute(command, envs = '') {
    def buildpack = 'golang-buildpack:0.0.8'
    def envText = envs=='' ? '' : "--env $envs"
    workDir = pwd()
    sh "docker run --rm -v $workDir:/go/src/github.com/kyma-project/kyma/ -w /go/src/github.com/kyma-project/kyma/$env.APP_FOLDER $envText ${env.DOCKER_REGISTRY}$buildpack /bin/bash -c '$command'"
}
