# Build the manager binary
FROM eu.gcr.io/kyma-project/external/golang:1.19.0-alpine3.16 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer

RUN go mod download

# Copy the go source
COPY cmd/webhook-certificate-handler/cronjob.go main.go
COPY pkg/webhook pkg/webhook


# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o out main.go

FROM scratch

COPY --from=builder /workspace/out /run

ENTRYPOINT ["/run"]
