BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-golang:go1.12
SCRIPTS_DIR = ../../../common/makefiles
APP_PATH = tests/contract/knative-channel-kafka
APP_NAME = knative-channel-kafka-contract-tests
# COMPONENT_DIR is a local path to component
include $(SCRIPTS_DIR)/generic-make-go.mk

test: ;

