// Code generated by mockery v1.0.0
package automock

import (
	internal "github.com/kyma-project/kyma/components/application-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// InstanceInserter is an autogenerated mock type for the instanceInserter type
type InstanceInserter struct {
	mock.Mock
}

// Insert provides a mock function with given fields: i
func (_m *InstanceInserter) Insert(i *internal.Instance) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.Instance) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
