// Code generated by mockery v1.0.0. DO NOT EDIT.
package automock

import mock "github.com/stretchr/testify/mock"
import shared "github.com/kyma-project/kyma/components/console-backend-service/internal/domain/shared"

// CmsRetriever is an autogenerated mock type for the CmsRetriever type
type CmsRetriever struct {
	mock.Mock
}

// ClusterDocsTopic provides a mock function with given fields:
func (_m *CmsRetriever) ClusterDocsTopic() shared.ClusterDocsTopicGetter {
	ret := _m.Called()

	var r0 shared.ClusterDocsTopicGetter
	if rf, ok := ret.Get(0).(func() shared.ClusterDocsTopicGetter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.ClusterDocsTopicGetter)
		}
	}

	return r0
}

// ClusterDocsTopicConverter provides a mock function with given fields:
func (_m *CmsRetriever) ClusterDocsTopicConverter() shared.GqlClusterDocsTopicConverter {
	ret := _m.Called()

	var r0 shared.GqlClusterDocsTopicConverter
	if rf, ok := ret.Get(0).(func() shared.GqlClusterDocsTopicConverter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.GqlClusterDocsTopicConverter)
		}
	}

	return r0
}

// DocsTopic provides a mock function with given fields:
func (_m *CmsRetriever) DocsTopic() shared.DocsTopicGetter {
	ret := _m.Called()

	var r0 shared.DocsTopicGetter
	if rf, ok := ret.Get(0).(func() shared.DocsTopicGetter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DocsTopicGetter)
		}
	}

	return r0
}

// DocsTopicConverter provides a mock function with given fields:
func (_m *CmsRetriever) DocsTopicConverter() shared.GqlDocsTopicConverter {
	ret := _m.Called()

	var r0 shared.GqlDocsTopicConverter
	if rf, ok := ret.Get(0).(func() shared.GqlDocsTopicConverter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.GqlDocsTopicConverter)
		}
	}

	return r0
}
