// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

import storage "github.com/kyma-project/kyma/components/console-backend-service/internal/domain/content/storage"

// OpenApiSpecGetter is an autogenerated mock type for the OpenApiSpecGetter type
type OpenApiSpecGetter struct {
	mock.Mock
}

// Find provides a mock function with given fields: kind, id
func (_m *OpenApiSpecGetter) Find(kind string, id string) (*storage.OpenApiSpec, error) {
	ret := _m.Called(kind, id)

	var r0 *storage.OpenApiSpec
	if rf, ok := ret.Get(0).(func(string, string) *storage.OpenApiSpec); ok {
		r0 = rf(kind, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.OpenApiSpec)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(kind, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
