// Code generated by mockery v1.0.0
package automock

import gqlschema "github.com/kyma-project/kyma/components/ui-api-layer/internal/gqlschema"

import mock "github.com/stretchr/testify/mock"
import v1beta1 "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1"

// GQLBindingConverter is an autogenerated mock type for the GQLBindingConverter type
type GQLBindingConverter struct {
	mock.Mock
}

// ToGQL provides a mock function with given fields: in
func (_m *GQLBindingConverter) ToGQL(in *v1beta1.ServiceBinding) *gqlschema.ServiceBinding {
	ret := _m.Called(in)

	var r0 *gqlschema.ServiceBinding
	if rf, ok := ret.Get(0).(func(*v1beta1.ServiceBinding) *gqlschema.ServiceBinding); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gqlschema.ServiceBinding)
		}
	}

	return r0
}
