// Code generated by mockery v1.0.0
package servicecatalog

import mock "github.com/stretchr/testify/mock"
import pager "github.com/kyma-project/kyma/components/console-backend-service/internal/pager"
import resource "github.com/kyma-project/kyma/components/console-backend-service/pkg/resource"
import status "github.com/kyma-project/kyma/components/console-backend-service/internal/domain/servicecatalog/status"
import v1beta1 "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1"

// mockServiceInstanceSvc is an autogenerated mock type for the serviceInstanceSvc type
type mockServiceInstanceSvc struct {
	mock.Mock
}

// Create provides a mock function with given fields: params
func (_m *mockServiceInstanceSvc) Create(params serviceInstanceCreateParameters) (*v1beta1.ServiceInstance, error) {
	ret := _m.Called(params)

	var r0 *v1beta1.ServiceInstance
	if rf, ok := ret.Get(0).(func(serviceInstanceCreateParameters) *v1beta1.ServiceInstance); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(serviceInstanceCreateParameters) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name, namespace
func (_m *mockServiceInstanceSvc) Delete(name string, namespace string) error {
	ret := _m.Called(name, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: name, namespace
func (_m *mockServiceInstanceSvc) Find(name string, namespace string) (*v1beta1.ServiceInstance, error) {
	ret := _m.Called(name, namespace)

	var r0 *v1beta1.ServiceInstance
	if rf, ok := ret.Get(0).(func(string, string) *v1beta1.ServiceInstance); ok {
		r0 = rf(name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsBindableWithClusterRefs provides a mock function with given fields: relatedClass, relatedPlan
func (_m *mockServiceInstanceSvc) IsBindableWithClusterRefs(relatedClass *v1beta1.ClusterServiceClass, relatedPlan *v1beta1.ClusterServicePlan) bool {
	ret := _m.Called(relatedClass, relatedPlan)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1beta1.ClusterServiceClass, *v1beta1.ClusterServicePlan) bool); ok {
		r0 = rf(relatedClass, relatedPlan)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsBindableWithLocalRefs provides a mock function with given fields: relatedClass, relatedPlan
func (_m *mockServiceInstanceSvc) IsBindableWithLocalRefs(relatedClass *v1beta1.ServiceClass, relatedPlan *v1beta1.ServicePlan) bool {
	ret := _m.Called(relatedClass, relatedPlan)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1beta1.ServiceClass, *v1beta1.ServicePlan) bool); ok {
		r0 = rf(relatedClass, relatedPlan)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// List provides a mock function with given fields: namespace, pagingParams
func (_m *mockServiceInstanceSvc) List(namespace string, pagingParams pager.PagingParams) ([]*v1beta1.ServiceInstance, error) {
	ret := _m.Called(namespace, pagingParams)

	var r0 []*v1beta1.ServiceInstance
	if rf, ok := ret.Get(0).(func(string, pager.PagingParams) []*v1beta1.ServiceInstance); ok {
		r0 = rf(namespace, pagingParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1beta1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, pager.PagingParams) error); ok {
		r1 = rf(namespace, pagingParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListForStatus provides a mock function with given fields: namespace, pagingParams, _a2
func (_m *mockServiceInstanceSvc) ListForStatus(namespace string, pagingParams pager.PagingParams, _a2 *status.ServiceInstanceStatusType) ([]*v1beta1.ServiceInstance, error) {
	ret := _m.Called(namespace, pagingParams, _a2)

	var r0 []*v1beta1.ServiceInstance
	if rf, ok := ret.Get(0).(func(string, pager.PagingParams, *status.ServiceInstanceStatusType) []*v1beta1.ServiceInstance); ok {
		r0 = rf(namespace, pagingParams, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1beta1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, pager.PagingParams, *status.ServiceInstanceStatusType) error); ok {
		r1 = rf(namespace, pagingParams, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: listener
func (_m *mockServiceInstanceSvc) Subscribe(listener resource.Listener) {
	_m.Called(listener)
}

// Unsubscribe provides a mock function with given fields: listener
func (_m *mockServiceInstanceSvc) Unsubscribe(listener resource.Listener) {
	_m.Called(listener)
}
