// Code generated by mockery v1.0.0
package automock

import gqlschema "github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema"

import mock "github.com/stretchr/testify/mock"
import v1 "k8s.io/api/core/v1"

// gqlServiceConverter is an autogenerated mock type for the gqlServiceConverter type
type gqlServiceConverter struct {
	mock.Mock
}

// ToGQL provides a mock function with given fields: in
func (_m *gqlServiceConverter) ToGQL(in *v1.Service) (*gqlschema.Service, error) {
	ret := _m.Called(in)

	var r0 *gqlschema.Service
	if rf, ok := ret.Get(0).(func(*v1.Service) *gqlschema.Service); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gqlschema.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Service) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
