APP_NAME = kubeless-integration
APP_PATH = tests/end-to-end/kubeless-integration
BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-golang:go1.12
SCRIPTS_DIR = ../../../common/makefiles
ENTRYPOINT = test-kubeless.go
# COMPONENT_DIR is a local path to component
include $(SCRIPTS_DIR)/generic-make-go.mk


test: ;

