// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import internal "github.com/kyma-project/kyma/components/application-broker/internal"
import mock "github.com/stretchr/testify/mock"

// ApplicationRemover is an autogenerated mock type for the ApplicationRemover type
type ApplicationRemover struct {
	mock.Mock
}

// Remove provides a mock function with given fields: name
func (_m *ApplicationRemover) Remove(name internal.ApplicationName) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(internal.ApplicationName) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
