// Code generated by mockery v1.0.0
package automock

import internal "github.com/kyma-project/kyma/components/application-broker/internal"
import mock "github.com/stretchr/testify/mock"

// RemoteEnvironmentUpserter is an autogenerated mock type for the RemoteEnvironmentUpserter type
type RemoteEnvironmentUpserter struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: re
func (_m *RemoteEnvironmentUpserter) Upsert(re *internal.RemoteEnvironment) (bool, error) {
	ret := _m.Called(re)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*internal.RemoteEnvironment) bool); ok {
		r0 = rf(re)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*internal.RemoteEnvironment) error); ok {
		r1 = rf(re)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
