// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// SCRelistRequester is an autogenerated mock type for the ScRelistRequester type
type SCRelistRequester struct {
	mock.Mock
}

// RequestRelist provides a mock function with given fields:
func (_m *SCRelistRequester) RequestRelist() {
	_m.Called()
}
