FROM 192.168.122.1:5000/java-runtime:11 as builder

ARG BUILD_DIR=/build
ARG SOURCE_DIR=/workspace/src
WORKDIR $BUILD_DIR

COPY $SOURCE_DIR/pom.xml $BUILD_DIR/handler-pom.xml
COPY $SOURCE_DIR/src/main/java/io/project/kyma/serverless/Handler.java $BUILD_DIR/src/main/java/io/project/kyma/serverless/handler/Handler.java

RUN mvn dependency:go-offline -f handler-pom.xml

#TODO: Reconsider: I delete this Handler class to compile only the new Handler class
RUN rm -f target/classes/io/project/kyma/serverless/Handler.class && mvn package -f pom.xml

FROM openjdk:11-jre

COPY --from=builder /build/target/kyma-java-runtime-0.0.1.jar /app.jar
COPY --from=builder /build/opentelemetry-javaagent.jar /opentelemetry-javaagent.jar

-Dotel.exporter.otlp.endpoint=http://127.0.0.1:4318
-Dotel.exporter.otlp.protocol=http/protobuf
-Dservice.name=emitter-local
ARG JVM_OPTS="-javaagent:./opentelemetry-javaagent.jar -Dotel.exporter.otlp.traces.endpoint=http://tracing-jaeger-collector.kyma-system.svc.cluster.local:4318 \
            -Dotel.exporter.otlp.protocol=http/protobuf \
             -Dservice.name=emitter"


ENTRYPOINT java ${JVM_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.jar --native
USER 1000
