// Code generated by failery v1.0.0. DO NOT EDIT.

package disabled

import context "context"
import gqlschema "github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema"

// Resolver is an autogenerated failing mock type for the Resolver type
type Resolver struct {
	err error
}

// NewResolver creates a new Resolver type instance
func NewResolver(err error) *Resolver {
	return &Resolver{err: err}
}

// AssetEventSubscription provides a failing mock function with given fields: ctx, namespace
func (_m *Resolver) AssetEventSubscription(ctx context.Context, namespace string) (<-chan gqlschema.RafterAssetEvent, error) {
	var r0 <-chan gqlschema.RafterAssetEvent
	var r1 error
	r1 = _m.err

	return r0, r1
}

// AssetFilesField provides a failing mock function with given fields: ctx, obj, filterExtensions
func (_m *Resolver) AssetFilesField(ctx context.Context, obj *gqlschema.RafterAsset, filterExtensions []string) ([]gqlschema.File, error) {
	var r0 []gqlschema.File
	var r1 error
	r1 = _m.err

	return r0, r1
}

// AssetGroupAssetsField provides a failing mock function with given fields: ctx, obj, types
func (_m *Resolver) AssetGroupAssetsField(ctx context.Context, obj *gqlschema.AssetGroup, types []string) ([]gqlschema.RafterAsset, error) {
	var r0 []gqlschema.RafterAsset
	var r1 error
	r1 = _m.err

	return r0, r1
}

// AssetGroupEventSubscription provides a failing mock function with given fields: ctx, namespace
func (_m *Resolver) AssetGroupEventSubscription(ctx context.Context, namespace string) (<-chan gqlschema.AssetGroupEvent, error) {
	var r0 <-chan gqlschema.AssetGroupEvent
	var r1 error
	r1 = _m.err

	return r0, r1
}

// ClusterAssetEventSubscription provides a failing mock function with given fields: ctx
func (_m *Resolver) ClusterAssetEventSubscription(ctx context.Context) (<-chan gqlschema.RafterClusterAssetEvent, error) {
	var r0 <-chan gqlschema.RafterClusterAssetEvent
	var r1 error
	r1 = _m.err

	return r0, r1
}

// ClusterAssetFilesField provides a failing mock function with given fields: ctx, obj, filterExtensions
func (_m *Resolver) ClusterAssetFilesField(ctx context.Context, obj *gqlschema.RafterClusterAsset, filterExtensions []string) ([]gqlschema.File, error) {
	var r0 []gqlschema.File
	var r1 error
	r1 = _m.err

	return r0, r1
}

// ClusterAssetGroupAssetsField provides a failing mock function with given fields: ctx, obj, types
func (_m *Resolver) ClusterAssetGroupAssetsField(ctx context.Context, obj *gqlschema.ClusterAssetGroup, types []string) ([]gqlschema.RafterClusterAsset, error) {
	var r0 []gqlschema.RafterClusterAsset
	var r1 error
	r1 = _m.err

	return r0, r1
}

// ClusterAssetGroupEventSubscription provides a failing mock function with given fields: ctx
func (_m *Resolver) ClusterAssetGroupEventSubscription(ctx context.Context) (<-chan gqlschema.ClusterAssetGroupEvent, error) {
	var r0 <-chan gqlschema.ClusterAssetGroupEvent
	var r1 error
	r1 = _m.err

	return r0, r1
}

// ClusterAssetGroupsQuery provides a failing mock function with given fields: ctx, viewContext, groupName
func (_m *Resolver) ClusterAssetGroupsQuery(ctx context.Context, viewContext *string, groupName *string) ([]gqlschema.ClusterAssetGroup, error) {
	var r0 []gqlschema.ClusterAssetGroup
	var r1 error
	r1 = _m.err

	return r0, r1
}
