// Code generated by mockery v1.0.0
package automock

import azblob "github.com/Azure/azure-storage-blob-go/2018-03-28/azblob"

import context "context"
import mock "github.com/stretchr/testify/mock"

// azureBlobClient is an autogenerated mock type for the azureBlobClient type
type azureBlobClient struct {
	mock.Mock
}

// DeleteBlockBlob provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *azureBlobClient) DeleteBlockBlob(_a0 context.Context, _a1 string, _a2 azblob.DeleteSnapshotsOptionType, _a3 azblob.BlobAccessConditions) (*azblob.BlobDeleteResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 *azblob.BlobDeleteResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, azblob.DeleteSnapshotsOptionType, azblob.BlobAccessConditions) *azblob.BlobDeleteResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*azblob.BlobDeleteResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, azblob.DeleteSnapshotsOptionType, azblob.BlobAccessConditions) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBlobsFlatSegment provides a mock function with given fields: _a0, _a1, _a2
func (_m *azureBlobClient) ListBlobsFlatSegment(_a0 context.Context, _a1 azblob.Marker, _a2 azblob.ListBlobsSegmentOptions) (*azblob.ListBlobsFlatSegmentResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *azblob.ListBlobsFlatSegmentResponse
	if rf, ok := ret.Get(0).(func(context.Context, azblob.Marker, azblob.ListBlobsSegmentOptions) *azblob.ListBlobsFlatSegmentResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*azblob.ListBlobsFlatSegmentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, azblob.Marker, azblob.ListBlobsSegmentOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
