{
 "title": "CMS AsyncAPI Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "apiserverdeploy", "query": "service-catalog-apiserver" },
   {
    "name": "controllerdeploy",
    "query": "service-catalog-controller-manager"
   },
   {
    "name": "etcd_cluster",
    "query": "service-catalog-etcd-stateful-client"
   },
   { "name": "etcddeploy", "query": "service-catalog-etcd-stateful" }
  ]
 },
 "panels": [
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"cms-cms-asyncapi-service\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"cms-cms-asyncapi-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"cms-cms-asyncapi-service-.*\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"cms-cms-asyncapi-service-.*\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"cms-cms-asyncapi-service-.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"cms-cms-asyncapi-service-.*\"}[1m]))",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"cms-cms-asyncapi-service-.*\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"cms-cms-asyncapi-service-.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"cms-cms-asyncapi-service-.*\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Number of mutated assets",
   "type": "graph",
   "description": "This chart shows a number of requests processed by the /convert endpoint in a given time series (in seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.005\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.01\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.025\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.05\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.1\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.25\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"0.5\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"1\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"2.5\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"5\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"10\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_bucket{le=\"+Inf\"}",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Number of validated assets",
   "type": "graph",
   "description": "This chart shows a number of requests processed by the /validate endpoint in a given time series (in seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.005\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.01\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.025\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.05\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.1\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.25\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"0.5\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"1\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"2.5\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"5\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"10\"}",
     "legendFormat": "{{le}} s"
    },
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_bucket{le=\"+Inf\"}",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Average mutation time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 39 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "cms_services_http_request_and_mutation_duration_seconds_sum/cms_services_http_request_and_mutation_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Average validation time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 39 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "cms_services_http_request_and_validation_duration_seconds_sum/cms_services_http_request_and_validation_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Number of returned HTTP response status codes from mutation endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cms_services_handle_mutation_status_code",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Number of returned HTTP response status codes from validation endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cms_services_handle_validation_status_code",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}