{
 "title": "Event Bus Subscription",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kyma_subscription_namespace",
    "label": "Namespace",
    "query": "label_values(total_kyma_subscriptions, exported_namespace)"
   },
   {
    "name": "kyma_subscription_name",
    "label": "Kyma Subscription Name",
    "query": "label_values(total_kyma_subscriptions{exported_namespace=\"$kyma_subscription_namespace\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kyma Subscription Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_kyma_subscriptions{exported_namespace=~\"$kyma_subscription_namespace\",name=~\"$kyma_subscription_name\",ready=\"true\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Knative Subscription Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_knative_subscriptions{exported_namespace=~\"$kyma_subscription_namespace\", name=~\"$kyma_subscription_name\", ready=\"true\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Knative Channels Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "total_knative_channels{name=~\"$kyma_subscription_name\"} OR on() vector(0)"
    }
   ]
  }
 ]
}