{
 "title": "Kubernetes API Server client dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "client", "label": "client", "query": "label_values(client)" }
  ]
 },
 "panels": [
  { "title": "Metrics per client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate by client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\", client=\"$client\"}[5m])) BY (client)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Request rate per by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\", client=\"$client\"}[5m])) BY (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Request rate per verb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\", client=\"$client\"}[5m])) BY (verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_count{code=~\"^(?:5..)$\", client=\"$client\"}[5m]) "
    }
   ]
  }
 ]
}