{
 "title": "Lambda Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(istio_requests_total{source_workload=~\"istio-ingressgateway*\"}, source_service)"
   },
   { "name": "source_version", "label": "Source Version", "query": "${VAR_SOURCE_VERSION}" },
   {
    "name": "destination",
    "label": "Destination",
    "query": "label_values(destination_service)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(kube_namespace_labels{label_istio_injection=\"enabled\"},namespace)"
   },
   {
    "name": "lambda_service",
    "label": "Lambda Function",
    "query": "label_values(kube_service_labels{label_created_by=\"kubeless\",namespace=\"$environment\"},service)"
   },
   {
    "name": "http_destination",
    "label": "HTTP Destination",
    "query": "label_values(istio_requests_total{destination_service=~\"$lambda_service.$environment.*\"}, destination_service)"
   },
   { "name": "destination_version", "label": "Destination Version", "query": "${VAR_DESTINATION_VERSION}" }
  ]
 },
 "panels": [
  { "title": "Lambda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "# $lambda_service.$environment\n"
  },
  {
   "title": "Rate by Service and Response Codes (2xx and 5xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(istio_requests_total{destination_service=~\"$http_destination\",response_code=~\"5.*\"}[2m])) by (destination_service, response_code) / sum(irate(istio_requests_total{destination_service=~\"$http_destination\"}[2m])) by (destination_service, response_code), \"destination_service\", \"$1\", \"destination_service\", \"$lambda_service.$environment.*\")",
     "legendFormat": "{{ response_code }} response code"
    },
    {
     "expr": "label_replace(sum(irate(istio_requests_total{destination_service=~\"$http_destination\",response_code=~\"2.*\"}[2m])) by (destination_service, response_code) / sum(irate(istio_requests_total{destination_service=~\"$http_destination\",}[2m])) by (destination_service, response_code), \"destination_service\", \"$1\", \"destination_service\", \"$lambda_service.$environment.*\")",
     "legendFormat": "{{ response_code }} response code"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 }, "content": "# Lambda Health\n" },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{pod_name=~\"$lambda_service.*\", container_name=\"$lambda_service\", container_name!=\"POD\"}) / sum (kube_pod_container_resource_limits_memory_bytes{pod=~\"$lambda_service.*\", container=\"$lambda_service\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage (Seconds)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 16 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_name=~\"$lambda_service\", pod_name=~\"$lambda_service.*\", namespace=\"$environment\"}[2m])  )"
    }
   ]
  },
  {
   "title": "Success Rate (2xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=~\"$http_destination\", response_code=~\"2.*\"}[2m])) / sum(rate(istio_requests_total{destination_service=~\"$http_destination\"}[2m])) "
    }
   ]
  },
  {
   "title": "Response Time by Service (Seconds)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{destination_service=~\"$http_destination\"}[2m])) by (destination_service, le))"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$lambda_service\",namespace=\"$environment\"}) without (deployment, pod)"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>HTTP Services</span>\n</div>"
  },
  { "title": "$http_destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "http_destination" },
  {
   "title": "Requests Rate by Service and Response Code",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_service=~\"$http_destination\"}[2m])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service}} -> {{ response_code }}"
    }
   ]
  },
  {
   "title": "Response Time by Service",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{destination_service=~\"$http_destination\"}[2m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} -> (p50)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{destination_service=~\"$http_destination\"}[2m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} -> ( (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{destination_service=~\"$http_destination\"}[2m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} -> ( (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{destination_service=~\"$http_destination\"}[2m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} -> ( (p99)"
    }
   ]
  }
 ]
}