{
 "title": "Loki-Promtail",
 "description": "Monitoring for logging",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "Loki push Kb/sec",
   "type": "graph",
   "description": "Shows data throughput rate in KB/s",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total[1m])/1024",
     "legendFormat": "kilobytes/sec"
    }
   ]
  },
  {
   "title": "Loki Queries/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_sum[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(promtail_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (rate(promtail_sent_bytes_total[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum (rate(promtail_encoded_bytes_total[5m]))",
     "legendFormat": "encoded"
    },
    {
     "expr": "sum(promtail_file_bytes_total - promtail_read_bytes_total)",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promtail_file_bytes_total - promtail_read_bytes_total > 100000",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}