{
 "title": "ORY Oathkeeper-maester",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"ory-oathkeeper-maester-metrics\"}"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"ory-oathkeeper-maester-metrics\"}"
    }
   ]
  },
  {
   "title": "GC invocations durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"ory-oathkeeper-maester-metrics\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "Heap in use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"ory-oathkeeper-maester-metrics\"}",
     "legendFormat": "Stack in use"
    },
    {
     "expr": "container_memory_usage_bytes{container_name=~\"oathkeeper-maester|istio-proxy\", pod_name=~\"ory-oathkeeper-maester.*\"}",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container_name=~\"oathkeeper-maester|istio-proxy\", pod_name=~\"ory-oathkeeper-maester.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Req/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=~\"ory-oathkeeper-maester-metrics.*\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "HTTP Error Rates (5xx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{service=~\"ory-oathkeeper-maester-metrics.*\",status_code=~\"5.*\"}[5m]) / rate(http_requests_total[5m])\n\n"
    }
   ]
  },
  {
   "title": "Request rate by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{service=\"ory-oathkeeper-maester-metrics\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"ory-oathkeeper-maester.*\"}[1m])))"
    }
   ]
  }
 ]
}