{
 "title": "Rafter Controller Manager",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "apiserverdeploy", "query": "service-catalog-apiserver" },
   {
    "name": "controllerdeploy",
    "query": "service-catalog-controller-manager"
   },
   {
    "name": "etcd_cluster",
    "query": "service-catalog-etcd-stateful-client"
   },
   { "name": "etcddeploy", "query": "service-catalog-etcd-stateful" }
  ]
 },
 "panels": [
  { "title": "Runtime Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Latency",
   "type": "graph",
   "description": "This chart shows how long a custom resource waited for processing by the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Average reconcile time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"asset\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"asset\"}[1m])",
     "legendFormat": "Asset"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"clusterasset\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"clusterasset\"}[1m])",
     "legendFormat": "ClusterAsset"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"bucket\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"bucket\"}[1m])",
     "legendFormat": "Bucket"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"clusterbucket\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"clusterbucket\"}[1m])",
     "legendFormat": "ClusterBucket"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"assetgroup\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"assetgroup\"}[1m])",
     "legendFormat": "AssetGroup"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"clusterassetgroup\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"clusterassetgroup\"}[1m])",
     "legendFormat": "ClusterAssetGroup"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "description": "This chart shows how many custom resources are waiting for processing by the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Average Queue Length" }
   ],
   "targets": [
    {
     "expr": "increase(workqueue_depth{job=\"rafter-rafter-controller-manager\", name=\"asset\"}[1m])",
     "legendFormat": "Asset"
    },
    {
     "expr": "increase(workqueue_depth{job=\"rafter-rafter-controller-manager\", name=\"bucket\"}[1m])",
     "legendFormat": "Bucket"
    },
    {
     "expr": "increase(workqueue_depth{job=\"rafter-rafter-controller-manager\", name=\"clusterasset\"}[1m])",
     "legendFormat": "ClusterAsset"
    },
    {
     "expr": "increase(workqueue_depth{job=\"rafter-rafter-controller-manager\", name=\"clusterbucket\"}[1m])",
     "legendFormat": "ClusterBucket"
    },
    {
     "expr": "increase(workqueue_depth{job=\"rafter-rafter-controller-manager\", name=\"assetgroup\"}[1m])",
     "legendFormat": "AssetGroup"
    },
    {
     "expr": "increase(workqueue_depth{job=\"rafter-rafter-controller-manager\", name=\"clusterassetgroup\"}[1m])",
     "legendFormat": "ClusterAssetGroup"
    }
   ]
  },
  {
   "title": "Reconcile Time",
   "type": "graph",
   "description": "This chart shows how long it took for the controller to process a custom resource.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Average reconcile time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"asset\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"asset\"}[1m])",
     "legendFormat": "Asset"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"clusterasset\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"clusterasset\"}[1m])",
     "legendFormat": "ClusterAsset"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"bucket\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"bucket\"}[1m])",
     "legendFormat": "Bucket"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"clusterbucket\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"clusterbucket\"}[1m])",
     "legendFormat": "ClusterBucket"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"assetgroup\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"assetgroup\"}[1m])",
     "legendFormat": "AssetGroup"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"rafter-rafter-controller-manager\", name=\"clusterassetgroup\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"rafter-rafter-controller-manager\", name=\"clusterassetgroup\"}[1m])",
     "legendFormat": "ClusterAssetGroup"
    }
   ]
  },
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"rafter-rafter-controller-manager\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"rafter-rafter-controller-manager\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"rafter-rafter-controller-manager-.*\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"rafter-rafter-controller-manager-.*\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"rafter-rafter-controller-manager-.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"rafter-rafter-controller-manager-.*\"}[1m]))",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"rafter-rafter-controller-manager-.*\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"rafter-rafter-controller-manager-.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"rafter-rafter-controller-manager-.*\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}