{
 "title": "Service Catalog",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "apiserverdeploy", "query": "service-catalog-apiserver" },
   {
    "name": "controllerdeploy",
    "query": "service-catalog-controller-manager"
   },
   {
    "name": "etcd_cluster",
    "query": "service-catalog-etcd-stateful-client"
   },
   { "name": "etcddeploy", "query": "service-catalog-etcd-stateful" }
  ]
 },
 "panels": [
  { "title": "[CONTROLLER] Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"service-catalog-catalog-controller-manager.*\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"service-catalog-catalog-controller-manager.*\"}",
     "legendFormat": "Requests: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"service-catalog-catalog-controller-manager.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network in [kB/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"kyma-system\",pod_name=~\"service-catalog-catalog-controller-manager.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"service-catalog-catalog-controller-manager.*\"}[1m]))",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"service-catalog-catalog-controller-manager.*\"}",
     "legendFormat": "Requests: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"service-catalog-catalog-controller-manager.*\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  { "title": "[CONTROLLER] Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "No. of classes and plans by Broker",
   "type": "graph",
   "description": "This diagram represent the number of service classes and service plans by Broker",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "No. of classes" }
   ],
   "targets": [
    {
     "expr": "servicecatalog_broker_service_class_count",
     "legendFormat": "classes from {{ broker }}"
    },
    {
     "expr": "servicecatalog_broker_service_plan_count",
     "legendFormat": "plans from {{ broker }} "
    }
   ]
  },
  {
   "title": "Requests by API Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servicecatalog_osb_request_count",
     "legendFormat": "{{ broker }} {{ method }} {{ status }}"
    }
   ]
  },
  {
   "title": "[WEBHOOK] Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"service-catalog-catalog-webhook.*\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"service-catalog-catalog-webhook.*\"}",
       "legendFormat": "Requests: {{ container }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"service-catalog-catalog-webhook.*\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Network in [kB/s]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"kyma-system\",pod_name=~\"service-catalog-catalog-webhook.*\"}[3m]))"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"service-catalog-catalog-webhook.*\"}[1m]))",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"service-catalog-catalog-webhook.*\"}",
       "legendFormat": "Requests: {{ container }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"service-catalog-catalog-webhook.*\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    }
   ]
  }
 ]
}