// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"
import v1 "k8s.io/api/apps/v1"

// gqlKymaVersionConverter is an autogenerated mock type for the gqlKymaVersionConverter type
type gqlKymaVersionConverter struct {
	mock.Mock
}

// ToKymaVersion provides a mock function with given fields: in
func (_m *gqlKymaVersionConverter) ToKymaVersion(in *v1.Deployment) string {
	ret := _m.Called(in)

	var r0 string
	if rf, ok := ret.Get(0).(func(*v1.Deployment) string); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
