// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	v1alpha1 "github.com/kyma-project/kyma/components/application-operator/pkg/apis/applicationconnector/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// extractor is an autogenerated mock type for the extractor type
type extractor struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0
func (_m *extractor) Do(_a0 interface{}) (*v1alpha1.Application, error) {
	ret := _m.Called(_a0)

	var r0 *v1alpha1.Application
	if rf, ok := ret.Get(0).(func(interface{}) *v1alpha1.Application); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
