{
 "title": "Connector-Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Resources and Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kyma-integration\",pod_name=~\"connector-service.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kyma-integration\",pod_name=~\"connector-service.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"kyma-integration\",pod_name=~\"connector-service.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"kyma-integration\",pod_name=~\"connector-service.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"connector-service\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"connector-service\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"connector-service\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"connector-service\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"connector-service\",namespace=\"kyma-integration\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  { "title": "Endpoints Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Average Endpoint Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "connector_service_endpoints_duration{exported_endpoint=\"/v1/remoteenvironments/{reName}/tokens\"})",
     "legendFormat": "AVG /v1/remoteenvironments/{reName}/tokens"
    },
    {
     "expr": "connector_service_endpoints_duration{exported_endpoint=\"/v1/remoteenvironments/{reName}/client-certs\"})",
     "legendFormat": "AVG /v1/remoteenvironments/{reName}/client-certs"
    },
    {
     "expr": "connector_service_endpoints_duration{exported_endpoint=\"/v1/remoteenvironments/{reName}/info\"})",
     "legendFormat": "AVG /v1/remoteenvironments/{reName}/info"
    }
   ]
  },
  { "title": "Endpoint Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Codes: /v1/remoteenvironments/{reName}/tokens",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "connector_service_endpoints_responses{exported_endpoint=\"/v1/remoteenvironments/{reName}/tokens\"}",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Codes: /v1/remoteenvironments/{reName}/info",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "connector_service_endpoints_responses{exported_endpoint=\"/v1/remoteenvironments/{reName}/info\"}",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Codes: /v1/remoteenvironments/{reName}/client-certs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "connector_service_endpoints_responses{exported_endpoint=\"/v1/remoteenvironments/{reName}/client-certs\"}",
     "legendFormat": "{{ code }}"
    }
   ]
  }
 ]
}