{
 "title": "Service Catalog",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "apiserverdeploy", "query": "core-catalog-apiserver" },
   {
    "name": "controllerdeploy",
    "query": "core-catalog-controller-manager"
   },
   {
    "name": "etcd_cluster",
    "query": "core-catalog-etcd-stateful-client"
   },
   { "name": "etcddeploy", "query": "core-catalog-etcd-stateful" }
  ]
 },
 "panels": [
  {
   "title": "[APISERVER] Available replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{deployment=\"$apiserverdeploy\",namespace=\"kyma-system\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "[CONTROLLER] Available replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{deployment=\"$controllerdeploy\",namespace=\"kyma-system\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Etcd has a leader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{service=\"$etcd_cluster\"})"
    }
   ]
  },
  {
   "title": "[APISERVER] Memory [MB]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kyma-system\",pod_name=~\"$apiserverdeploy.*\"}) / 1024^2",
     "legendFormat": "Memory [GB]"
    }
   ]
  },
  {
   "title": "[APISERVER] CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kyma-system\",pod_name=~\"$apiserverdeploy.*\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "[APISERVER] Network in [kB/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"kyma-system\",pod_name=~\"$apiserverdeploy.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "[CONTROLLER] Memory [MB]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kyma-system\",pod_name=~\"$controllerdeploy.*\"}) / 1024^2",
     "legendFormat": "Memory [GB]"
    }
   ]
  },
  {
   "title": "[CONTROLLER] CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kyma-system\",pod_name=~\"$controllerdeploy.*\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "[CONTROLLER] Network in [kB/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"kyma-system\",pod_name=~\"$controllerdeploy.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "[ETCD] Memory [MB]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=\"kyma-system\",pod_name=~\"$etcddeploy.*\"})  by (pod_name))/ 1024^2",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "[ETCD] CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kyma-system\",pod_name=~\"$etcddeploy.*\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "[ETCD] Network in [kB/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"kyma-system\",pod_name=~\"$etcddeploy.*\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "[APISERVER] go metrics", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"core-catalog-apiserver\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"core-catalog-apiserver\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"core-catalog-apiserver\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"$apiserverdeploy\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"$apiserverdeploy\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"$apiserverdeploy\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"$apiserverdeploy\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"$apiserverdeploy\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}