{
 "title": "Kyma / Service Catalog Add-ons / Binding Usage Controller",
 "tags": [
  "service-catalog",
  "kyma"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "apiserverdeploy", "query": "service-catalog-apiserver" },
   {
    "name": "controllerdeploy",
    "query": "service-catalog-controller-manager"
   },
   {
    "name": "etcd_cluster",
    "query": "service-catalog-etcd-stateful-client"
   },
   { "name": "etcddeploy", "query": "service-catalog-etcd-stateful" }
  ]
 },
 "panels": [
  { "title": "Runtime Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Average reconcile time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_latency_sum{controller=\"service_binding_usage_controller\"}[1m]) / rate(controller_runtime_reconcile_latency_count{controller=\"service_binding_usage_controller\"}[1m])",
     "legendFormat": "ServiceBindingUsageController"
    },
    {
     "expr": "rate(controller_runtime_reconcile_latency_sum{controller=\"usage_kind_controller\"}[1m]) / rate(controller_runtime_reconcile_latency_count{controller=\"usage_kind_controller\"}[1m])",
     "legendFormat": "UsageKindController"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Average Queue Length" }
   ],
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_queue_length{controller=\"service_binding_usage_controller\"}[1m])",
     "legendFormat": "ServiceBindingUsageController"
    },
    {
     "expr": "increase(controller_runtime_reconcile_queue_length{controller=\"usage_kind_controller\"}[1m])",
     "legendFormat": "UsageKindController"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Amount of errors" }
   ],
   "targets": [
    {
     "expr": "controller_runtime_reconcile_errors_total{controller=\"service_binding_usage_controller\"}",
     "legendFormat": "ServiceBindingUsageController"
    },
    {
     "expr": "controller_runtime_reconcile_errors_total{controller=\"usage_kind_controller\"}",
     "legendFormat": "UsageKindController"
    }
   ]
  },
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "{{`{{quantile}}`}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"service-catalog-addons-service-binding-usage-controller\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"service-catalog-addons-service-binding-usage-controller\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{pod=~\"service-catalog-addons-service-binding-usage-controller.*\", container!=\"POD\"})",
     "legendFormat": "Current: {{`{{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"service-catalog-addons-service-binding-usage-controller.*\"}",
     "legendFormat": "Requested: {{`{{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"service-catalog-addons-service-binding-usage-controller.*\"}",
     "legendFormat": "Limit: {{`{{container}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"service-catalog-addons-service-binding-usage-controller.*\"}[1m]))",
     "legendFormat": "{{`{{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"service-catalog-addons-service-binding-usage-controller.*\"}",
     "legendFormat": "Requested: {{`{{container}}`}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"service-catalog-addons-service-binding-usage-controller.*\"}",
     "legendFormat": "Limit: {{`{{container}}`}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"service-catalog-addons-service-binding-usage-controller.*\"}[1m])))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}