// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Collector is an autogenerated mock type for the Collector type
type Collector struct {
	mock.Mock
}

// AddObservation provides a mock function with given fields: observation, labelValues
func (_m *Collector) AddObservation(observation float64, labelValues ...string) {
	_va := make([]interface{}, len(labelValues))
	for _i := range labelValues {
		_va[_i] = labelValues[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, observation)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
