// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import gqlschema "github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema"

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "github.com/kyma-project/kyma/components/helm-broker/pkg/apis/addons/v1alpha1"

// gqlClusterAddonsConfigurationConverter is an autogenerated mock type for the gqlClusterAddonsConfigurationConverter type
type gqlClusterAddonsConfigurationConverter struct {
	mock.Mock
}

// ToGQL provides a mock function with given fields: item
func (_m *gqlClusterAddonsConfigurationConverter) ToGQL(item *v1alpha1.ClusterAddonsConfiguration) *gqlschema.AddonsConfiguration {
	ret := _m.Called(item)

	var r0 *gqlschema.AddonsConfiguration
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterAddonsConfiguration) *gqlschema.AddonsConfiguration); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gqlschema.AddonsConfiguration)
		}
	}

	return r0
}
