// Code generated by mockery v1.0.0
package automock

import gqlschema "github.com/kyma-project/kyma/components/ui-api-layer/internal/gqlschema"

import mock "github.com/stretchr/testify/mock"

// envLister is an autogenerated mock type for the envLister type
type envLister struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *envLister) List() ([]gqlschema.Environment, error) {
	ret := _m.Called()

	var r0 []gqlschema.Environment
	if rf, ok := ret.Get(0).(func() []gqlschema.Environment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gqlschema.Environment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListForRemoteEnvironment provides a mock function with given fields: reName
func (_m *envLister) ListForRemoteEnvironment(reName string) ([]gqlschema.Environment, error) {
	ret := _m.Called(reName)

	var r0 []gqlschema.Environment
	if rf, ok := ret.Get(0).(func(string) []gqlschema.Environment); ok {
		r0 = rf(reName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gqlschema.Environment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(reName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
