// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	csrf "github.com/kyma-project/kyma/components/application-gateway/internal/csrf"
	authorization "github.com/kyma-project/kyma/components/application-gateway/pkg/authorization"

	mock "github.com/stretchr/testify/mock"
)

// TokenStrategyFactory is an autogenerated mock type for the TokenStrategyFactory type
type TokenStrategyFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: authorizationStrategy, csrfTokenEndpointURL
func (_m *TokenStrategyFactory) Create(authorizationStrategy authorization.Strategy, csrfTokenEndpointURL string) csrf.TokenStrategy {
	ret := _m.Called(authorizationStrategy, csrfTokenEndpointURL)

	var r0 csrf.TokenStrategy
	if rf, ok := ret.Get(0).(func(authorization.Strategy, string) csrf.TokenStrategy); ok {
		r0 = rf(authorizationStrategy, csrfTokenEndpointURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(csrf.TokenStrategy)
		}
	}

	return r0
}
