ARG ALPINE_KUBECTL_VERSION="v20200617-32c1f3ff"
FROM eu.gcr.io/kyma-project/test-infra/alpine-kubectl:$ALPINE_KUBECTL_VERSION

LABEL source="git@github.com:kyma-project/kyma.git"

ADD ./crds /etc/crds
