// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/kyma-project/kyma/components/function-controller/pkg/apis/serverless/v1alpha1"
)

// StatsCollector is an autogenerated mock type for the StatsCollector type
type StatsCollector struct {
	mock.Mock
}

// UpdateFunctionStatusGauge provides a mock function with given fields: f, cond
func (_m *StatsCollector) UpdateFunctionStatusGauge(f *v1alpha1.Function, cond v1alpha1.Condition) {
	_m.Called(f, cond)
}
