// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/kyma/components/application-gateway/pkg/apperrors"
	mock "github.com/stretchr/testify/mock"

	proxy "github.com/kyma-project/kyma/components/application-gateway/pkg/proxy"
)

// TargetConfigProvider is an autogenerated mock type for the TargetConfigProvider type
type TargetConfigProvider struct {
	mock.Mock
}

// GetDestinationConfig provides a mock function with given fields: id
func (_m *TargetConfigProvider) GetDestinationConfig(id string) (proxy.ProxyDestinationConfig, apperrors.AppError) {
	ret := _m.Called(id)

	var r0 proxy.ProxyDestinationConfig
	if rf, ok := ret.Get(0).(func(string) proxy.ProxyDestinationConfig); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(proxy.ProxyDestinationConfig)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}
