// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import apperrors "kyma-project.io/compass-runtime-agent/internal/apperrors"

import docstopic "kyma-project.io/compass-runtime-agent/internal/kyma/apiresources/assetstore/docstopic"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id string) apperrors.AppError {
	ret := _m.Called(id)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) apperrors.AppError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// Put provides a mock function with given fields: id, apiType, spec, specFormat, specCategory
func (_m *Service) Put(id string, apiType docstopic.ApiType, spec []byte, specFormat docstopic.SpecFormat, specCategory docstopic.SpecCategory) apperrors.AppError {
	ret := _m.Called(id, apiType, spec, specFormat, specCategory)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, docstopic.ApiType, []byte, docstopic.SpecFormat, docstopic.SpecCategory) apperrors.AppError); ok {
		r0 = rf(id, apiType, spec, specFormat, specCategory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}
