// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
import v1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"

// ServiceInstanceClient is an autogenerated mock type for the ServiceInstanceClient type
type ServiceInstanceClient struct {
	mock.Mock
}

// List provides a mock function with given fields: opts
func (_m *ServiceInstanceClient) List(opts v1.ListOptions) (*v1beta1.ServiceInstanceList, error) {
	ret := _m.Called(opts)

	var r0 *v1beta1.ServiceInstanceList
	if rf, ok := ret.Get(0).(func(v1.ListOptions) *v1beta1.ServiceInstanceList); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.ServiceInstanceList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
