// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"
)

// ServiceInstanceClient is an autogenerated mock type for the ServiceInstanceClient type
type ServiceInstanceClient struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, opts
func (_m *ServiceInstanceClient) List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ServiceInstanceList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *v1beta1.ServiceInstanceList
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *v1beta1.ServiceInstanceList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.ServiceInstanceList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
