# Dockerfile for running tests locally with scripts/run_tests.sh script

FROM golang:1.13-alpine as builder

ENV SRC_DIR=/go/src/github.com/kyma-project/kyma/tests/compass-runtime-agent

RUN apk add --no-cache curl

WORKDIR $SRC_DIR

COPY scripts/entrypoint.sh .
COPY test.test .

ENTRYPOINT ["./entrypoint.sh"]
