#!/usr/bin/env bash

kubectl delete -n kyma-system authorizationpolicys.security.istio.io connector-service
kubectl delete -n kyma-system clusterroles.rbac.authorization.k8s.io application-registry-role
kubectl delete -n kyma-system clusterroles.rbac.authorization.k8s.io central-application-connectivity-validator-role
kubectl delete -n kyma-system clusterroles.rbac.authorization.k8s.io connection-token-handler-clusterrole
kubectl delete -n kyma-system clusterrolebindings.rbac.authorization.k8s.io application-registry-rolebinding
kubectl delete -n kyma-system clusterrolebindings.rbac.authorization.k8s.io central-application-connectivity-validator-rolebinding
kubectl delete -n kyma-system clusterrolebindings.rbac.authorization.k8s.io connection-token-handler-clusterrolebinding
kubectl delete -n kyma-system configmap application-registry-dashboard
kubectl delete -n kyma-system configmap connector-service-dashboard
kubectl delete -n kyma-system configmap ory-oathkeeper-rules
kubectl delete -n kyma-system configmap revocations-config
kubectl delete -n kyma-system deployments.apps application-registry
kubectl delete -n kyma-system deployments.apps central-application-connectivity-validator
kubectl delete -n kyma-system deployments.apps connection-token-handler
kubectl delete -n kyma-system deployments.apps connector-service
kubectl delete -n kyma-system gateways.networking.istio.io kyma-gateway-application-connector
kubectl delete -n kyma-system horizontalpodautoscalers.autoscaling central-application-connectivity-validator
kubectl delete -n kyma-system jobs.batch application-connector-certs-setup-job
kubectl delete -n kyma-system peerauthentications.security.istio.io application-registry-policy
kubectl delete -n kyma-system peerauthentications.security.istio.io connector-service-policy
kubectl delete -n kyma-system podsecuritypolicys.policy application-registry
kubectl delete -n kyma-system podsecuritypolicys.policy connection-token-handler
kubectl delete -n kyma-system podsecuritypolicys.policy connector-service
kubectl delete -n kyma-system prometheusrules.monitoring.coreos.com monitoring-kyma-prometheus.rules
kubectl delete -n kyma-system roles.rbac.authorization.k8s.io application-connector-certs-setup-job-ca-cert-role
kubectl delete -n kyma-system roles.rbac.authorization.k8s.io application-connector-certs-setup-job-connector-cert-role
kubectl delete -n kyma-system roles.rbac.authorization.k8s.io application-registry-role
kubectl delete -n kyma-system roles.rbac.authorization.k8s.io connector-service-connector-service-app-ca-role
kubectl delete -n kyma-system roles.rbac.authorization.k8s.io connector-service-role
kubectl delete -n kyma-system rolebindings.rbac.authorization.k8s.io application-connector-certs-setup-job-ca-cert-rolebinding
kubectl delete -n kyma-system rolebindings.rbac.authorization.k8s.io application-connector-certs-setup-job-connector-cert-rolebinding
kubectl delete -n kyma-system rolebindings.rbac.authorization.k8s.io application-registry-rolebinding
kubectl delete -n kyma-system rolebindings.rbac.authorization.k8s.io connector-service-connector-service-app-ca-rolebinding
kubectl delete -n kyma-system rolebindings.rbac.authorization.k8s.io connector-service-rolebinding
kubectl delete -n kyma-system service application-registry-external-api
kubectl delete -n kyma-system service application-registry-metrics
kubectl delete -n kyma-system service central-application-connectivity-validator
kubectl delete -n kyma-system service connector-service-external-api
kubectl delete -n kyma-system service connector-service-internal-api
kubectl delete -n kyma-system service connector-service-metrics
kubectl delete -n kyma-system serviceaccount application-connector-certs-setup-job
kubectl delete -n kyma-system serviceaccount central-application-connectivity-validator
kubectl delete -n kyma-system serviceaccount connection-token-handler
kubectl delete -n kyma-system serviceaccount connector-service
kubectl delete -n kyma-system servicemonitors.monitoring.coreos.com application-registry
kubectl delete -n kyma-system servicemonitors.monitoring.coreos.com connector-service
kubectl delete -n kyma-system virtualservices.networking.istio.io central-application-connectivity-validator
kubectl delete -n kyma-system virtualservices.networking.istio.io connector-service
kubectl delete -n kyma-system virtualservices.networking.istio.io connector-service-mtls
