// Code generated by mockery v1.0.0
package automock

import internal "github.com/kyma-project/kyma/components/application-broker/internal"
import mock "github.com/stretchr/testify/mock"

// remoteEnvironmentFinder is an autogenerated mock type for the remoteEnvironmentFinder type
type RemoteEnvironmentFinder struct {
	mock.Mock
}

// FindOneByServiceID provides a mock function with given fields: id
func (_m *RemoteEnvironmentFinder) FindOneByServiceID(id internal.RemoteServiceID) (*internal.RemoteEnvironment, error) {
	ret := _m.Called(id)

	var r0 *internal.RemoteEnvironment
	if rf, ok := ret.Get(0).(func(internal.RemoteServiceID) *internal.RemoteEnvironment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.RemoteEnvironment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.RemoteServiceID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
